// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:7000' | 'http://{host}:{port}' | (string & {});
};

/**
 * Point-in-time database health report. `integrity` is `ok` or
 * the first problem line `PRAGMA integrity_check` reported.
 * Sizes are bytes on disk; `wal_bytes` is 0 when no WAL sidecar
 * exists. `freelist_pages` counts reclaimable pages — `vacuum`
 * returns them to the filesystem.
 *
 */
export type DbHealth = {
    integrity: string;
    size_bytes: number;
    wal_bytes: number;
    freelist_pages: number;
    page_count: number;
    checked_at: string;
};

/**
 * RFC 9457 (Problem Details for HTTP APIs) error body, returned as
 * `application/problem+json` for every 4xx/5xx the API surfaces. `type`
 * is a stable URI under
 * `https://github.com/sound-barrier/recall/problems/` that clients can
 * switch on; `instance` is the request path. Members beyond those listed
 * here are RFC 9457 §3.2 extension members (the schema stays open).
 *
 */
export type ProblemDetails = {
    /**
     * A URI identifying the problem class.
     */
    type: string;
    /**
     * Short, human-readable summary of the problem class.
     */
    title: string;
    /**
     * The HTTP status code, duplicated in the body for convenience.
     */
    status: number;
    /**
     * Human-readable explanation specific to this occurrence.
     */
    detail?: string;
    /**
     * The request path that produced the problem.
     */
    instance?: string;
    /**
     * §3.2 extension — per-field validation failures, present on a
     * malformed request body.
     *
     */
    errors?: Array<FieldError>;
    /**
     * §3.2 extension — the asset(s) whose SHA-256 sidecar verification
     * failed (the data-update 422).
     *
     */
    failed_assets?: Array<string>;
};

/**
 * One offending request field and why it was rejected.
 */
export type FieldError = {
    /**
     * The request-body field name.
     */
    field: string;
    /**
     * Why the field was rejected.
     */
    detail: string;
};

/**
 * Snapshot of the in-flight parse run. The resync anchor for the
 * async parse pipeline — read after an SSE reconnect or a page
 * reload to restore the parse panel without replaying events.
 *
 */
export type ActiveParse = {
    /**
     * Whether a parse is currently in flight.
     */
    running: boolean;
    /**
     * Screenshot files OCR'd so far this run.
     */
    done: number;
    /**
     * Total files to process this run (0 when idle).
     */
    total: number;
    /**
     * "new" (default parse) or "all" (re-parse); empty when idle.
     */
    scope: string;
};

/**
 * Which sides a match was disrupted on — used by both `leavers`
 * and `throwers`.
 * - `self`: the user themselves (their own data is incomplete,
 * or they were the one throwing).
 * - `team`: an ally.
 * - `enemy`: an opponent.
 *
 * A SET, not a single value: a match can carry a thrower on both
 * teams at once, and the leaver-exit quick-add records "a
 * teammate left, then I left" as `["team", "self"]`. An empty
 * array (or an omitted field) means "not tagged"; order is not
 * significant and duplicates are collapsed server-side.
 *
 */
export type DisruptionSides = Array<'self' | 'team' | 'enemy'>;

/**
 * Queue format the match was played in. The single-set
 * `PUT /matches/{match_key}/queue` endpoint only accepts
 * non-empty values; revert to "queue not set" via the matching
 * DELETE.
 *
 */
export type QueueTypeEnum = 'role' | 'open';

/**
 * Same as `QueueTypeEnum` plus the empty-string sentinel for
 * the bulk endpoint. Empty string clears every listed match's
 * queue row (bulk Clear); the single-set DELETE doesn't apply
 * to multi-match writes, so the same effect rides through the
 * bulk endpoint via this enum value.
 *
 */
export type QueueTypeBulkEnum = 'role' | 'open' | '';

/**
 * Play-mode override for one match. The single-set
 * `PUT /matches/{match_key}/play-mode` endpoint only accepts
 * non-empty values; revert to "follow parser" via the matching
 * DELETE.
 *
 */
export type PlayModeEnum = 'quickplay' | 'competitive';

/**
 * Same as `PlayModeEnum` plus the empty-string sentinel for the
 * bulk endpoint. Empty string clears every listed match's
 * play-mode override (bulk Clear).
 *
 */
export type PlayModeBulkEnum = 'quickplay' | 'competitive' | '';

/**
 * Provenance of a match record.
 * - `ocr`: parsed from screenshots, unedited.
 * - `ocr_edited`: parsed, then user-corrected via the override
 * layer (`PUT /matches/{match_key}/data`). `edited_fields` lists
 * the overridden paths.
 * - `manual`: hand-entered (`POST /matches`); no screenshot rows.
 *
 */
export type MatchSourceEnum = 'ocr' | 'ocr_edited' | 'manual';

/**
 * Match outcome.
 */
export type ResultEnum = 'victory' | 'defeat' | 'draw';

/**
 * Full user override set for `PUT /matches/{match_key}/data`. Inline
 * edits send the whole current set; a per-field revert is the same
 * request with that field omitted. A scalar present (even `0` / `""`)
 * means "override to this value"; omitting it means "use the OCR
 * value". Kept separate from the parsed rows, so a `DELETE` on the
 * same path restores the original.
 *
 */
export type UserMatchDataInput = {
    map?: string;
    hero?: string;
    eliminations?: number;
    assists?: number;
    deaths?: number;
    damage?: number;
    healing?: number;
    mitigation?: number;
    result?: ResultEnum;
    final_score?: string;
    date?: string;
    finished_at?: string;
    game_length?: string;
    rank?: string;
    level?: number;
    rank_progress?: number;
    change_percent?: number;
    /**
     * Heroes-played LIST override (position 0 = primary). Replaces
     * the OCR roster wholesale when present.
     *
     */
    heroes?: Array<UserHeroInput>;
    /**
     * Per-cell stat overrides, applied INDEPENDENTLY of the heroes
     * list — a stat edit never implies a roster swap.
     *
     */
    hero_stats?: Array<UserHeroStatInput>;
    /**
     * Per-hero SR overrides (editing an OCR rank screen).
     */
    sr?: Array<UserHeroSrInput>;
    modifiers?: Array<string>;
};

export type UserHeroInput = {
    hero: string;
    percent_played?: number;
    play_time?: string;
    /**
     * 0 = primary.
     */
    position?: number;
};

export type UserHeroStatInput = {
    hero: string;
    stat_key: string;
    value: number;
};

export type UserHeroSrInput = {
    hero: string;
    sr: number;
    change: number;
};

/**
 * Hand-entered match for users without OCR. The server derives the
 * `match_key` from `played_at` (default: now) and returns the created
 * MatchRecord. `heroes[0]` is the primary hero.
 *
 * Only `map` and `result` are required. `heroes`, `play_mode`, and
 * `queue_type` are optional because the leaver-exit quick-add records
 * a match Overwatch erased from history, where the user knows the map
 * and the outcome and nothing else — inventing a hero or a queue there
 * would be fabricating data. A value that IS supplied is still
 * validated; only omission is free.
 *
 */
export type ManualMatchInput = {
    map: string;
    play_mode?: PlayModeEnum;
    queue_type?: QueueTypeEnum;
    /**
     * Heroes played; first is the primary (need not be ordered by play
     * time). Omit entirely for a quick-add with no hero recorded.
     *
     */
    heroes?: Array<string>;
    result: ResultEnum;
    /**
     * When the match was played (RFC 3339). Defaults to now. The
     * timestamp's WALL CLOCK in its stated offset drives the
     * `match_key` plus `date` / `finished_at` — send the player's
     * local time with its offset so manual rows sit on the same
     * naive-local time axis as OCR rows (which store the on-screen
     * local clock).
     *
     */
    played_at?: string;
    rank?: ManualRankInput;
    leavers?: DisruptionSides;
    throwers?: DisruptionSides;
    /**
     * Optional Overwatch replay code; written to the match annotation.
     */
    replay_code?: string;
    /**
     * Optional free-form note; written to the match annotation.
     */
    note?: string;
    /**
     * Optional free-form tags; written to the match annotation.
     */
    tags?: Array<string>;
    /**
     * The squad / group the user played with; written to the match
     * annotation (stored verbatim, so `Apollo#11234` keeps its case).
     *
     */
    members?: Array<string>;
};

/**
 * Competitive rank the match ended on. Omit for quickplay.
 */
export type ManualRankInput = {
    tier?: string;
    division?: number;
    /**
     * % into the division.
     */
    progress?: number;
    /**
     * % gained / lost this match.
     */
    change_percent?: number;
    demotion_protection?: boolean;
};

export type IgnoredScreenshot = {
    /**
     * Filename the suppress-list keys on. Same shape as the
     * `filename` path parameter on the per-file ignore endpoints.
     *
     */
    filename: string;
    /**
     * Server-assigned timestamp captured when the row was added.
     * ISO 8601 (RFC 3339); SQLite's `CURRENT_TIMESTAMP` rounds to
     * the nearest second so two ignores within the same second
     * share an identical value and tie-break on filename ASC.
     *
     */
    ignored_at: string;
};

export type FailedFile = {
    /**
     * Filename the failure ledger keys on. Same shape as the
     * `filename` path parameter on the per-file ignore endpoints.
     *
     */
    filename: string;
    /**
     * The most recent attempt's error message, verbatim.
     */
    error: string;
    /**
     * Failed parse runs since `first_failed_at`.
     */
    attempts: number;
    /**
     * Timestamp of the first recorded failure (RFC 3339).
     */
    first_failed_at: string;
    /**
     * Timestamp of the most recent failure (RFC 3339).
     */
    last_failed_at: string;
};

export type FolderPath = {
    /**
     * The configured screenshots folder. The GET response can
     * return an empty string when no folder has been configured;
     * the PUT request body inlines its own minLength: 1 schema.
     *
     */
    path: string;
};

export type ProbeResult = {
    /**
     * True when at least one candidate directory existed.
     */
    found: boolean;
    /**
     * First existing candidate path. Empty when `found` is false.
     *
     */
    path?: string;
    /**
     * Ordered list of candidate paths inspected by the probe.
     * Useful diagnostic when `found` is false — surfaces "we
     * looked here and here" rather than a generic miss.
     *
     */
    tried: Array<string>;
};

/**
 * One entry in the Windows screenshot-source picker. Each card
 * the user sees corresponds to one canonical capture method.
 *
 */
export type NamedCandidate = {
    /**
     * Stable identifier — `nvidia` (Nvidia Overlay), `prntscn`
     * (OW PrntScn default), `snip` (Win Snip tool), `steam`
     * (Steam-installed OW). Frontend keys cards off this.
     *
     */
    name: 'nvidia' | 'prntscn' | 'snip' | 'steam';
    /**
     * Human-readable display label rendered as the card title
     * ("Nvidia Overlay", "OW default", etc.).
     *
     */
    label: string;
    /**
     * Resolved first-existing path variant for this source.
     * When no variant exists, lifts to the canonical first
     * path so the "not found" card still has a path to
     * display.
     *
     */
    path: string;
    /**
     * True iff the resolved `path` is a real directory the
     * current process can stat. Drives the card's status dot
     * (green when true, gray when false) and whether clicking
     * it commits the path via PUT
     * /api/v1/settings/screenshots-folder.
     *
     */
    exists: boolean;
};

/**
 * Shared base for the game-data status type. Carries the diff
 * fields (added/removed × heroes/maps/sources) + `has_update`
 * so consumers don't repeat the same six array fields.
 * `GameDataStatus` extends this with the applied-commit
 * identifier via `allOf`.
 *
 */
export type RosterDiff = {
    /**
     * True when the channel's published version differs from
     * the version applied on disk. Always true when nothing
     * has been applied yet (no manifest entry for this
     * channel).
     *
     */
    has_update: boolean;
    added_heroes?: Array<string>;
    removed_heroes?: Array<string>;
    added_maps?: Array<string>;
    removed_maps?: Array<string>;
    added_sources?: Array<string>;
    removed_sources?: Array<string>;
    added_seasons?: Array<string>;
    removed_seasons?: Array<string>;
    /**
     * Season names whose window (start/end) changed.
     */
    changed_seasons?: Array<string>;
};

export type UpdateInfo = {
    /**
     * True when a GitHub API call completed successfully.
     * False on network failure — show nothing in that case.
     *
     */
    checked: boolean;
    /**
     * True when the running version is a dev build. The
     * latest release is then informational context, not an
     * upgrade prompt.
     *
     */
    dev_build: boolean;
    /**
     * True when the latest release is newer than the running
     * version (only meaningful when dev_build=false).
     *
     */
    available: boolean;
    latest: string;
    url: string;
    /**
     * Display names from the upcoming release's
     * `recall-<version>-heroes.yaml` asset, verified
     * against the published SHA-256 sidecar. Empty
     * when the YAML fetch fails, the sidecar
     * mismatches, or the upgrade isn't applicable
     * (current build is already the latest). The
     * frontend's Unknown-tab "Reference data gaps"
     * section pivots this into a per-card "Update to
     * v<X> to recognise <name>" CTA.
     *
     */
    latest_heroes?: Array<string>;
    /**
     * Display names from the upcoming release's
     * `recall-<version>-maps.yaml` asset — same
     * lifecycle as latest_heroes.
     *
     */
    latest_maps?: Array<string>;
    /**
     * Screenshot-source names extracted from the
     * release's `recall-<version>-screenshot_sources.yaml`
     * asset. Used by the update-check modal to surface
     * newly-supported capture tools.
     *
     */
    latest_sources?: Array<string>;
    /**
     * RFC3339 timestamp recording when this install
     * last received a successful CheckForUpdate
     * response. Drives the "haven't checked in a
     * while" banner. Empty on the very first check.
     *
     */
    last_checked_at?: string;
    /**
     * First ~500 chars of the GitHub release `body`
     * (Markdown source), surfaced in the update-check
     * modal under a "more on GitHub" link. The frontend
     * interpolates this via Vue's default escaping —
     * never `v-html`.
     *
     */
    release_notes?: string;
    game_data: GameDataStatus;
    /**
     * True when this install can swap its own binary in place —
     * the Windows Wails desktop build on a non-dev version, in a
     * user-writable install directory. The About dialog shows an
     * "Install update" button (driving POST
     * /api/v1/system/self-update) only then; otherwise it falls
     * back to the "Open release page" link. Always false in server
     * mode, for dev builds, on non-Windows builds (Recall ships
     * Windows only), and for legacy machine-wide Windows installs
     * under Program Files.
     *
     */
    can_self_update: boolean;
};

/**
 * Comparison between the user's currently-loaded game data
 * (heroes / maps / capture-tool sources) and the live main
 * channel published at https://sound-barrier.github.io/recall/data/.
 * `commit_sha` is the 7-char short SHA from the Pages-published
 * `data/version.json`; empty means the Pages fetch failed (the
 * FE shows a "main unreachable" state). `applied_commit` is
 * empty when the user has never applied an update (the install
 * is on the binary's embedded data). `has_update` is true when
 * commit_sha != applied_commit.
 *
 */
export type GameDataStatus = RosterDiff & {
    /**
     * 7-char short SHA of the currently-published main
     * commit. Empty means the main channel was unreachable.
     *
     */
    commit_sha: string;
    /**
     * ISO 8601 committer date from the Pages-published
     * version.json — surfaced as "main @ abc1234 · 2 d ago"
     * in the modal.
     *
     */
    committed_at?: string;
    /**
     * 7-char short SHA from the manifest's
     * applied_main_commit field. Empty when the user has
     * never applied an update.
     *
     */
    applied_commit: string;
    /**
     * RFC3339 timestamp of the last successful apply.
     */
    applied_at?: string;
};

/**
 * Returned by POST /api/v1/system/data-update on success. Lists
 * the actual differences applied — the modal renders these as
 * the success-state summary.
 *
 */
export type DataUpdateResult = {
    /**
     * 7-char short commit SHA from Pages-published
     * data/version.json that the apply pulled from.
     *
     */
    applied_commit: string;
    added_heroes?: Array<string>;
    removed_heroes?: Array<string>;
    added_maps?: Array<string>;
    removed_maps?: Array<string>;
    added_sources?: Array<string>;
    removed_sources?: Array<string>;
    added_seasons?: Array<string>;
    removed_seasons?: Array<string>;
    /**
     * Season names whose window (start/end) changed.
     */
    changed_seasons?: Array<string>;
};

export type DataLocation = {
    /**
     * Root directory Recall reads/writes from. Honors
     * `RECALL_DATA_DIR`; otherwise the platform user-config
     * directory.
     *
     */
    base_dir: string;
    /**
     * Absolute path to `settings.json`.
     */
    settings_path: string;
    /**
     * Absolute path to the SQLite database file.
     */
    database_path: string;
    /**
     * Currently-configured screenshots folder. Empty string
     * when not yet set.
     *
     */
    screenshots_dir?: string;
};

/**
 * Outcome of a merge import (`POST /api/v1/imports`): how many
 * matches were added versus skipped because their key already
 * existed locally.
 *
 */
export type ImportSummary = {
    /**
     * Matches added to the local database.
     */
    imported: number;
    /**
     * Matches skipped because their key already existed.
     */
    skipped: number;
};

/**
 * One match — assembled by JOINing the per-screenshot-type rows
 * that share the same `match_key`. Identity is `match_key`; no
 * separate `id` exists because no single row underlies a match
 * anymore.
 *
 */
export type MatchRecord = {
    /**
     * Stable identity. Either `match-<ISO-timestamp>` (from the
     * earliest screenshot's filename, with all date/time
     * separators normalised to `-` so the whole key is URL-safe
     * without encoding) or `unmatched-<filename>` for files
     * whose names didn't parse as timestamps.
     *
     */
    match_key: string;
    /**
     * Every screenshot filename that fed this match.
     */
    source_files: Array<string>;
    /**
     * Per-source-file screenshot classification. Populated at
     * parse time. May be absent on rows parsed before this column
     * landed.
     *
     */
    source_types?: {
        [key: string]: ScreenshotType;
    };
    /**
     * Per-source-file timestamp (ISO8601) of when each screenshot
     * was first inserted into the DB. Stable across subsequent
     * re-parses of the same match. May be absent on rows / files
     * persisted before this column landed.
     *
     */
    source_parsed_at?: {
        [key: string]: string;
    };
    /**
     * Per-source-file screenshots_dirs row id the file was ingested
     * from. Frontends build `/_screenshot/{dir_id}/{filename}` URLs
     * from this map so the screenshot handler can serve the right
     * directory even after the user changes their screenshots
     * folder (re-install, move, profile switch). Absent for rows
     * where the dir was unset at parse time; clients should send
     * `0` to fall back to the currently-configured screenshots
     * folder.
     *
     */
    source_dir_ids?: {
        [key: string]: number;
    };
    /**
     * The source filename whose image is actually present on disk and
     * best represents the match (SUMMARY, else TEAMS, else any source
     * file) — the one the leaf-row hover preview should show. Resolved
     * at read time against the live filesystem. Absent when no source
     * image exists on disk (a manual match, a data-only import, or a
     * screenshot that was deleted or moved); clients must not request a
     * `/_screenshot/...` URL for the match in that case.
     *
     */
    thumbnail_file?: string;
    /**
     * Match-level timestamp (ISO8601) of when the match record
     * was first inserted into the DB. Stable across subsequent
     * re-parses so the UI can display "parsed on X" without the
     * value shifting when a later screenshot is added.
     *
     */
    parsed_at?: string;
    data: MatchResult;
    source?: MatchSourceEnum;
    /**
     * Dotted paths of fields the user overrode on an OCR match
     * (e.g. `data.damage`,
     * `data.heroes_played.junkrat.stats.rip_tire_kill`), so the UI
     * can mark each with a revert affordance. Absent for pure OCR
     * and for manual matches — the Manual badge conveys provenance.
     *
     */
    edited_fields?: Array<string>;
    annotation?: MatchAnnotation;
    /**
     * True iff the user soft-deleted this match via
     * `PUT /api/v1/matches/{match_key}/visibility`. Omitted (or
     * false) for normal records. The per-screenshot parent rows
     * are untouched — only the aggregator hides the surface.
     *
     */
    hidden?: boolean;
    /**
     * Who reviewed this match's VOD: `self` (the user) or
     * `coach` (a coach). Omitted entirely when the match has
     * not been reviewed (the implicit third state). Set via
     * `PUT /api/v1/matches/{match_key}/review`, cleared via
     * `DELETE` on the same path.
     *
     */
    reviewed_by?: 'self' | 'coach';
    /**
     * Server-stamped timestamp of the last review-status
     * upsert. Drives the dossier's "days since last review"
     * widget. Omitted when the match is unreviewed.
     *
     */
    reviewed_at?: string;
    /**
     * Queue format the match was played in: `role` (5v5 role
     * queue) or `open` (6v6 open queue). Auto-detected from the
     * teams players-per-team count; a user override set
     * via `PUT /api/v1/matches/{match_key}/queue` takes
     * precedence, and `DELETE` on the same path reverts to the
     * detected value. Omitted entirely when neither a detection
     * nor an override exists.
     *
     */
    queue_type?: QueueTypeEnum;
    /**
     * Match's play mode: `quickplay` (casual) or `competitive`
     * (ranked). Set ONLY from the `match_play_mode` user-
     * override aux table — parser-written `data.playlist` and
     * rank-row presence do not surface here. New matches
     * default to "Not set" until the user explicitly toggles
     * via the right-panel radiogroup; omitted from JSON when
     * no override row exists.
     *
     */
    play_mode?: PlayModeEnum;
    /**
     * True iff the user starred this match (`pinned_matches`
     * sidecar). The Matches list renders pinned matches in a
     * leading "Pinned" section above the date groups. Omitted
     * when false.
     *
     */
    pinned?: boolean;
    /**
     * True iff the resolver couldn't pin this screenshot to a
     * single match (EAD signature match in the 5-30 min
     * ambiguous window, or multiple candidates inside 30 min),
     * or the end-of-parse duplicate sweep demoted a freshly
     * created match whose full TEAMS stat line duplicated an
     * existing match's within 7 days. The `match_key` carries
     * the `ambiguous-<filename>` sentinel and the `candidates`
     * array lists the possible matches the user can pick from
     * in the Unknown tab.
     *
     */
    ambiguous?: boolean;
    /**
     * Candidate matches this ambiguous screenshot could belong
     * to. Only present when `ambiguous=true`. Sorted by
     * `distance_seconds` ascending.
     *
     */
    candidates?: Array<AmbiguousCandidate>;
};

/**
 * Automatic-backup schedule + newest-snapshot status. See
 * `GET /api/v1/settings/auto-backup`.
 *
 */
export type AutoBackupStatus = {
    /**
     * Effective interval — -1 disabled, else days.
     */
    interval_days: number;
    /**
     * Timestamp of the newest automatic snapshot (parsed from its
     * filename). Omitted when no automatic snapshot exists yet.
     *
     */
    last_backup_at?: string;
    /**
     * True when the scheduler is enabled and the newest snapshot is
     * missing or older than the interval.
     *
     */
    stale: boolean;
};

/**
 * One candidate match an ambiguous screenshot could belong to.
 * Populated by the resolver when EAD-bridge ambiguity is
 * detected, or by the end-of-parse duplicate sweep when a fresh
 * match's TEAMS stat line duplicates an existing match's;
 * surfaced to the user in the Unknown tab.
 *
 */
export type AmbiguousCandidate = {
    /**
     * The candidate match's `match_key`.
     */
    match_key: string;
    /**
     * |Δt| between the ambiguous screenshot's filename timestamp
     * and the candidate match's anchor timestamp, in seconds.
     *
     */
    distance_seconds: number;
    /**
     * Why the candidate was proposed. `duplicate_stats` means the
     * end-of-parse duplicate sweep found the capture's full TEAMS
     * stat line (eliminations, assists, deaths, damage, healing,
     * mitigation) exactly equal to this candidate match's, 30
     * minutes to 7 days apart — almost certainly a re-capture of
     * the same match. Omitted for ordinary EAD-bridge /
     * timestamp-window ambiguity. Derived from `distance_seconds`
     * server-side, never stored.
     *
     */
    reason?: 'duplicate_stats';
    /**
     * One source file from the candidate match (its earliest
     * screenshot) so the picker UI can render a thumbnail next
     * to the candidate. Omitted when the candidate match is not
     * present in the current result set (e.g. hidden when
     * show-hidden is off).
     *
     */
    representative_source_file?: string;
    /**
     * `screenshots_dirs` row id that owns
     * `representative_source_file`. Pairs with the filename to
     * build a `/_screenshot/<id>/<filename>` URL. Omitted when
     * the file is missing or zero.
     *
     */
    representative_dir_id?: number;
};

/**
 * User-curated per-match metadata embedded in a `MatchRecord`.
 * `leavers` and `throwers` are always present (possibly empty
 * arrays) so clients can read their length without a null check;
 * `note` / `replay_code` / `members` / `tags` are omitted when
 * empty (the server marshals them `omitempty`). The row only
 * exists in the database if at least one field carries content;
 * absence of the row is signalled by a 404 on
 * `GET /api/v1/matches/{match_key}/annotation`, and the whole
 * annotation object is omitted from `MatchRecord` when the match is
 * unannotated.
 *
 */
export type MatchAnnotation = {
    leavers: DisruptionSides;
    throwers: DisruptionSides;
    /**
     * Free-text per-match commentary.
     */
    note?: string;
    /**
     * Overwatch six-character replay ID. Stored verbatim.
     */
    replay_code?: string;
    /**
     * BattleTags of group members for this match.
     */
    members?: Array<string>;
    /**
     * Free-form match labels (lowercase, deduped). `stack`,
     * `stream`, `placement` are the conventional three; users
     * can add anything. Drives the FilterRail "Tags" filter.
     *
     */
    tags?: Array<string>;
    /**
     * Server-set timestamp of when the annotation was last upserted.
     */
    annotated_at?: string;
};

/**
 * Classification of one screenshot:
 * * `summary` — post-match SUMMARY tab
 * * `teams` — in-game or post-match TEAMS screen
 * * `personal` — post-match PERSONAL tab
 * * `rank` — competitive RANK PROGRESS screen
 * * `all_heroes` — the PERSONAL "All Heroes" aggregate view.
 * Recognized but deliberately not stored (its totals duplicate
 * the TEAMS screen and its stat-card icons defeat the OCR), so
 * it appears in the live parse-progress event but never in a
 * match's `source_types`.
 * * `unknown` — the OCR classifier couldn't pick a type from
 * the file. Surfaced in the Unknown tab for triage; the
 * row's per-screenshot data lives in `unknown_screenshots`
 * until the user resolves it (re-OCR, manual attribution,
 * or drop).
 *
 */
export type ScreenshotType = 'summary' | 'teams' | 'personal' | 'rank' | 'all_heroes' | 'unknown';

/**
 * All parsed data for a match, merged across its source files.
 */
export type MatchResult = {
    /**
     * e.g. "rialto"
     */
    map?: string;
    /**
     * Raw OCR'd map-name text preserved when the matcher
     * rejected the candidate as unknown (no canonical match in
     * `pkg/parser/maps.yaml`). `map == "" && map_raw != ""`
     * is the "Unknown map" signal that drives the leaf-row
     * chip and detail-panel banner.
     *
     */
    map_raw?: string;
    /**
     * e.g. "control"
     */
    game_mode?: string;
    playlist?: 'competitive' | 'quickplay' | 'unranked' | '';
    role?: 'tank' | 'dps' | 'support' | '';
    /**
     * Primary (most-played) hero
     */
    hero?: string;
    /**
     * Raw OCR'd hero-name text preserved when the matcher
     * rejected the candidate as unknown (no canonical match in
     * `pkg/parser/heroes.yaml`). `hero == "" && hero_raw != ""`
     * is the "Unknown hero" signal. A future YAML release that
     * adds the hero is picked up at the next boot's
     * re-aggregate without re-running Tesseract.
     *
     */
    hero_raw?: string;
    eliminations?: number;
    assists?: number;
    deaths?: number;
    damage?: number;
    healing?: number;
    mitigation?: number;
    result?: 'victory' | 'defeat' | 'draw' | '';
    final_score?: string;
    date?: string;
    /**
     * HH:MM 24h as shown by the OW client.
     */
    finished_at?: string;
    game_length?: string;
    /**
     * Canonical UTC instant (RFC 3339), derived at parse time from
     * date+finished_at via the machine's timezone identity. Absent when
     * no instant is derivable. The client renders it in the viewer's
     * current timezone; date/finished_at remain the naive local clock.
     *
     */
    played_at_utc?: string;
    heroes_played?: Array<HeroPlay>;
    performance?: Performance;
    rank?: string;
    level?: number;
    modifiers?: Array<string>;
    rank_progress?: number;
    /**
     * Percentage the rank moved this match (signed).
     */
    change_percent?: number;
    sr?: Array<HeroSr>;
};

export type HeroPlay = {
    hero: string;
    percent_played?: number;
    play_time?: string;
    /**
     * Hero-specific stats keyed by snake_case label.
     */
    stats?: {
        [key: string]: number;
    };
};

export type HeroSr = {
    hero: string;
    sr: number;
    /**
     * Signed delta this match
     */
    change: number;
};

export type Performance = {
    eliminations?: PerformanceStat;
    assists?: PerformanceStat;
    deaths?: PerformanceStat;
};

export type PerformanceStat = {
    total: number;
    avg_per_10min?: number;
};

export type ProfilesResponse = {
    /**
     * The currently-active profile name.
     */
    active: string;
    /**
     * Every known profile name, sorted alphabetically (the
     * order matches `slices.Sort` on the slice the
     * `*Profiles.List` method returns).
     *
     */
    profiles: Array<string>;
    /**
     * The read-only profiles (the tour's sample "test" profile).
     * The client disables parse / import / restore / manual-add /
     * delete affordances for these — writes are rejected with 409.
     *
     */
    immutable: Array<string>;
};

export type SeedTestProfileResponse = {
    /**
     * The seeded profile's name (always "test").
     */
    profile: string;
    /**
     * Number of matches now in the sample profile.
     */
    matches: number;
    /**
     * True when "test" already held matches and was reused untouched
     * (no reseed); false when it was freshly seeded.
     *
     */
    already_seeded: boolean;
};

export type TesseractStatus = {
    /**
     * The currently-configured path.
     */
    path: string;
    /**
     * True iff `path` resolves to a working binary.
     */
    found: boolean;
    /**
     * Tesseract `--version` output (e.g. "5.4.1"). Empty when not found.
     */
    version: string;
    /**
     * True iff the detected major version is 5.x (the only officially supported series).
     */
    supported: boolean;
    /**
     * Description of the last detection failure, if any.
     */
    error: string;
    /**
     * Platform default path (Homebrew on macOS, /usr/bin on Linux, etc.).
     */
    default: string;
    /**
     * Host's `runtime.GOOS` value — `darwin`, `linux`, `windows`,
     * `freebsd`, etc. The frontend uses it to surface only the
     * install-path guidance that matches the host, instead of
     * listing every OS in one confusing paragraph.
     *
     */
    platform: string;
};

export type EnabledFlag = {
    enabled: boolean;
};

export type CloseBehaviorFlag = {
    /**
     * true → closing the window quits Recall; false → hide to the tray
     * (folder watcher keeps running). macOS ignores this.
     *
     */
    exit_on_close: boolean;
};

/**
 * Match identity — same `match_key` value exposed in
 * `MatchRecord`. URL-safe: the canonical form replaces every
 * legacy colon separator with a dash, so no percent-encoding
 * is required for paste-in-URL use
 * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
 * and `ambiguous-<filename>` variants the embedded filename
 * still needs the usual encoding for spaces / unicode.
 *
 */
export type MatchKey = string;

export type ClearMatchesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Preserve the `ignored_screenshots` suppress list across
         * the wipe. Defaults to false (the historical factory-reset
         * semantic). Strict — anything other than `true` / `false`
         * / absent returns 400.
         *
         */
        keep_ignored?: boolean;
    };
    url: '/api/v1/matches';
};

export type ClearMatchesErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type ClearMatchesError = ClearMatchesErrors[keyof ClearMatchesErrors];

export type ClearMatchesResponses = {
    /**
     * All matches cleared.
     */
    204: void;
};

export type ClearMatchesResponse = ClearMatchesResponses[keyof ClearMatchesResponses];

export type GetMatchResultsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Max records per page. Clamped to [1, 1000].
         */
        limit?: number;
        /**
         * The previous page's last `match_key`. Returned records
         * start strictly after it. Empty / absent = first page.
         * A cursor matching no record (mistyped, or the row was
         * deleted between pages) returns the empty page — the
         * pagination terminator. Re-anchor from the first page if
         * more records were expected; pagination never silently
         * restarts.
         *
         */
        cursor?: string;
    };
    url: '/api/v1/matches';
};

export type GetMatchResultsErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type GetMatchResultsError = GetMatchResultsErrors[keyof GetMatchResultsErrors];

export type GetMatchResultsResponses = {
    /**
     * Array of match records.
     */
    200: Array<MatchRecord>;
};

export type GetMatchResultsResponse = GetMatchResultsResponses[keyof GetMatchResultsResponses];

export type CreateManualMatchData = {
    body: ManualMatchInput;
    path?: never;
    query?: never;
    url: '/api/v1/matches';
};

export type CreateManualMatchErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * A match already exists at that time; pick a different minute.
     */
    409: unknown;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type CreateManualMatchError = CreateManualMatchErrors[keyof CreateManualMatchErrors];

export type CreateManualMatchResponses = {
    /**
     * The created manual match.
     */
    201: MatchRecord;
};

export type CreateManualMatchResponse = CreateManualMatchResponses[keyof CreateManualMatchResponses];

export type HardDeleteMatchData = {
    body?: never;
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}';
};

export type HardDeleteMatchErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type HardDeleteMatchError = HardDeleteMatchErrors[keyof HardDeleteMatchErrors];

export type HardDeleteMatchResponses = {
    /**
     * Match removed (or already absent).
     */
    204: void;
};

export type HardDeleteMatchResponse = HardDeleteMatchResponses[keyof HardDeleteMatchResponses];

export type GetMatchByKeyData = {
    body?: never;
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}';
};

export type GetMatchByKeyErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Match not found.
     */
    404: unknown;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type GetMatchByKeyError = GetMatchByKeyErrors[keyof GetMatchByKeyErrors];

export type GetMatchByKeyResponses = {
    /**
     * Match found.
     */
    200: MatchRecord;
};

export type GetMatchByKeyResponse = GetMatchByKeyResponses[keyof GetMatchByKeyResponses];

export type SetMatchVisibilityData = {
    body: {
        /**
         * True to hide; false to unhide.
         */
        hidden: boolean;
    };
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}/visibility';
};

export type SetMatchVisibilityErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type SetMatchVisibilityError = SetMatchVisibilityErrors[keyof SetMatchVisibilityErrors];

export type SetMatchVisibilityResponses = {
    /**
     * Visibility updated.
     */
    204: void;
};

export type SetMatchVisibilityResponse = SetMatchVisibilityResponses[keyof SetMatchVisibilityResponses];

export type SetMatchPinData = {
    body: {
        /**
         * True to pin; false to unpin.
         */
        pinned: boolean;
    };
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}/pin';
};

export type SetMatchPinErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type SetMatchPinError = SetMatchPinErrors[keyof SetMatchPinErrors];

export type SetMatchPinResponses = {
    /**
     * Pin state updated.
     */
    204: void;
};

export type SetMatchPinResponse = SetMatchPinResponses[keyof SetMatchPinResponses];

export type ResolveAmbiguousMatchData = {
    body: {
        /**
         * The match the user picked. Must be one of the
         * recorded candidates or a `match-<...>` key.
         *
         */
        resolved_to: string;
    };
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}/resolution';
};

export type ResolveAmbiguousMatchErrors = {
    /**
     * Invalid input — `match_key` doesn't start with
     * `ambiguous-`, `resolved_to` is not one of the recorded
     * candidates and isn't a freshly-minted `match-<...>` key,
     * or the request body fails JSON validation.
     *
     */
    400: unknown;
    /**
     * The requested resource was not found.
     */
    404: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type ResolveAmbiguousMatchError = ResolveAmbiguousMatchErrors[keyof ResolveAmbiguousMatchErrors];

export type ResolveAmbiguousMatchResponses = {
    /**
     * Resolution applied.
     */
    204: void;
};

export type ResolveAmbiguousMatchResponse = ResolveAmbiguousMatchResponses[keyof ResolveAmbiguousMatchResponses];

export type DeleteMatchAnnotationData = {
    body?: never;
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}/annotation';
};

export type DeleteMatchAnnotationErrors = {
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type DeleteMatchAnnotationError = DeleteMatchAnnotationErrors[keyof DeleteMatchAnnotationErrors];

export type DeleteMatchAnnotationResponses = {
    /**
     * Annotation cleared (or already absent).
     */
    204: void;
};

export type DeleteMatchAnnotationResponse = DeleteMatchAnnotationResponses[keyof DeleteMatchAnnotationResponses];

export type SetMatchAnnotationData = {
    body: {
        /**
         * Which sides had someone leave. An all-empty body
         * (every field blank) is rejected with 409 — use
         * `DELETE` to clear the row.
         *
         */
        leavers?: DisruptionSides;
        /**
         * Which sides had someone throwing.
         */
        throwers?: DisruptionSides;
        /**
         * Free-text per-match commentary. `null` = empty.
         */
        note?: string;
        /**
         * Overwatch six-character replay ID. No format validation server-side. `null` = empty.
         */
        replay_code?: string;
        /**
         * BattleTags of group members for this match. The server
         * trims whitespace, drops empty strings, and deduplicates;
         * the composite-PK on the child table catches any
         * duplicates that slip through. `null` is treated as an
         * empty list (clear members) — equivalent to `[]`.
         *
         */
        members?: Array<string>;
        /**
         * Free-form labels applied to the match. `stack`,
         * `stream`, and `placement` are the conventional
         * three (the UI surfaces them as quick-add toggles)
         * but any string is accepted. Server lowercases +
         * trims + deduplicates before persistence so
         * `Stack` and `stack` collapse to one entry. Drives
         * the FilterRail "Tags" multi-select. `null` is
         * treated as an empty list (clear tags) — equivalent
         * to `[]`.
         *
         */
        tags?: Array<string>;
    };
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}/annotation';
};

export type SetMatchAnnotationErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * The request was syntactically valid, but the resource state or
     * a payload value prevents the action (e.g. duplicate profile
     * name, screenshots directory not configured, invalid Tesseract
     * binary path, non-candidate resolution target).
     *
     */
    409: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type SetMatchAnnotationError = SetMatchAnnotationErrors[keyof SetMatchAnnotationErrors];

export type SetMatchAnnotationResponses = {
    /**
     * Annotation persisted.
     */
    204: void;
};

export type SetMatchAnnotationResponse = SetMatchAnnotationResponses[keyof SetMatchAnnotationResponses];

export type ResetMatchDataData = {
    body?: never;
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}/data';
};

export type ResetMatchDataErrors = {
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type ResetMatchDataError = ResetMatchDataErrors[keyof ResetMatchDataErrors];

export type ResetMatchDataResponses = {
    /**
     * Overrides cleared.
     */
    204: void;
};

export type ResetMatchDataResponse = ResetMatchDataResponses[keyof ResetMatchDataResponses];

export type UpdateMatchDataData = {
    body: UserMatchDataInput;
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}/data';
};

export type UpdateMatchDataErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * A map or hero override isn't in the Overwatch roster.
     */
    409: unknown;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type UpdateMatchDataError = UpdateMatchDataErrors[keyof UpdateMatchDataErrors];

export type UpdateMatchDataResponses = {
    /**
     * Override set persisted.
     */
    204: void;
};

export type UpdateMatchDataResponse = UpdateMatchDataResponses[keyof UpdateMatchDataResponses];

export type ClearMatchReviewData = {
    body?: never;
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}/review';
};

export type ClearMatchReviewErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type ClearMatchReviewError = ClearMatchReviewErrors[keyof ClearMatchReviewErrors];

export type ClearMatchReviewResponses = {
    /**
     * Review tag cleared (or already absent).
     */
    204: void;
};

export type ClearMatchReviewResponse = ClearMatchReviewResponses[keyof ClearMatchReviewResponses];

export type SetMatchReviewData = {
    body: {
        /**
         * Who reviewed this match's VOD. To revert to "not
         * reviewed", call DELETE on this path instead of
         * PUTing an empty string.
         *
         */
        reviewed_by: 'self' | 'coach';
    };
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}/review';
};

export type SetMatchReviewErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type SetMatchReviewError = SetMatchReviewErrors[keyof SetMatchReviewErrors];

export type SetMatchReviewResponses = {
    /**
     * Review status updated.
     */
    204: void;
};

export type SetMatchReviewResponse = SetMatchReviewResponses[keyof SetMatchReviewResponses];

export type ClearMatchQueueData = {
    body?: never;
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}/queue';
};

export type ClearMatchQueueErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type ClearMatchQueueError = ClearMatchQueueErrors[keyof ClearMatchQueueErrors];

export type ClearMatchQueueResponses = {
    /**
     * Queue tag cleared (or already absent).
     */
    204: void;
};

export type ClearMatchQueueResponse = ClearMatchQueueResponses[keyof ClearMatchQueueResponses];

export type SetMatchQueueData = {
    body: {
        queue_type: QueueTypeEnum;
    };
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}/queue';
};

export type SetMatchQueueErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type SetMatchQueueError = SetMatchQueueErrors[keyof SetMatchQueueErrors];

export type SetMatchQueueResponses = {
    /**
     * Queue type updated.
     */
    204: void;
};

export type SetMatchQueueResponse = SetMatchQueueResponses[keyof SetMatchQueueResponses];

export type ClearMatchPlayModeData = {
    body?: never;
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}/play-mode';
};

export type ClearMatchPlayModeErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type ClearMatchPlayModeError = ClearMatchPlayModeErrors[keyof ClearMatchPlayModeErrors];

export type ClearMatchPlayModeResponses = {
    /**
     * Play-mode override cleared (or already absent).
     */
    204: void;
};

export type ClearMatchPlayModeResponse = ClearMatchPlayModeResponses[keyof ClearMatchPlayModeResponses];

export type SetMatchPlayModeData = {
    body: {
        play_mode: PlayModeEnum;
    };
    path: {
        /**
         * Match identity — same `match_key` value exposed in
         * `MatchRecord`. URL-safe: the canonical form replaces every
         * legacy colon separator with a dash, so no percent-encoding
         * is required for paste-in-URL use
         * (e.g. `match-2026-05-10T22-21-11`). For `unmatched-<filename>`
         * and `ambiguous-<filename>` variants the embedded filename
         * still needs the usual encoding for spaces / unicode.
         *
         */
        match_key: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_key}/play-mode';
};

export type SetMatchPlayModeErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type SetMatchPlayModeError = SetMatchPlayModeErrors[keyof SetMatchPlayModeErrors];

export type SetMatchPlayModeResponses = {
    /**
     * Play-mode override updated.
     */
    204: void;
};

export type SetMatchPlayModeResponse = SetMatchPlayModeResponses[keyof SetMatchPlayModeResponses];

export type BulkSetMatchQueueData = {
    body: {
        /**
         * The set of match_keys to write. May be empty
         * (no-op); duplicates within the slice are tolerated
         * — the per-key upsert is idempotent.
         *
         */
        match_keys: Array<string>;
        queue_type: QueueTypeBulkEnum;
    };
    path?: never;
    query?: never;
    url: '/api/v1/matches/queue';
};

export type BulkSetMatchQueueErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type BulkSetMatchQueueError = BulkSetMatchQueueErrors[keyof BulkSetMatchQueueErrors];

export type BulkSetMatchQueueResponses = {
    /**
     * All listed matches' queue type updated.
     */
    204: void;
};

export type BulkSetMatchQueueResponse = BulkSetMatchQueueResponses[keyof BulkSetMatchQueueResponses];

export type BulkSetMatchPlayModeData = {
    body: {
        /**
         * The set of match_keys to write. May be empty
         * (no-op); duplicates within the slice are
         * tolerated.
         *
         */
        match_keys: Array<string>;
        play_mode: PlayModeBulkEnum;
    };
    path?: never;
    query?: never;
    url: '/api/v1/matches/play-mode';
};

export type BulkSetMatchPlayModeErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type BulkSetMatchPlayModeError = BulkSetMatchPlayModeErrors[keyof BulkSetMatchPlayModeErrors];

export type BulkSetMatchPlayModeResponses = {
    /**
     * All listed matches' play mode updated.
     */
    204: void;
};

export type BulkSetMatchPlayModeResponse = BulkSetMatchPlayModeResponses[keyof BulkSetMatchPlayModeResponses];

export type ParseScreenshotsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * `new` (default) parses only files not in the DB.
         * `all` re-OCRs every file. Other values return 400.
         *
         */
        scope?: 'new' | 'all';
    };
    url: '/api/v1/parses';
};

export type ParseScreenshotsErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * The request was syntactically valid, but the resource state or
     * a payload value prevents the action (e.g. duplicate profile
     * name, screenshots directory not configured, invalid Tesseract
     * binary path, non-candidate resolution target).
     *
     */
    409: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type ParseScreenshotsError = ParseScreenshotsErrors[keyof ParseScreenshotsErrors];

export type ParseScreenshotsResponses = {
    /**
     * Parse accepted and started; subscribe to events for progress + completion.
     */
    202: unknown;
};

export type CancelParseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/parses/active';
};

export type CancelParseErrors = {
    /**
     * The request was syntactically valid, but the resource state or
     * a payload value prevents the action (e.g. duplicate profile
     * name, screenshots directory not configured, invalid Tesseract
     * binary path, non-candidate resolution target).
     *
     */
    409: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type CancelParseError = CancelParseErrors[keyof CancelParseErrors];

export type CancelParseResponses = {
    /**
     * Cancellation signalled; SSE `parse-cancelled` follows once the loop unwinds.
     */
    202: unknown;
};

export type GetActiveParseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/parses/active';
};

export type GetActiveParseErrors = {
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type GetActiveParseError = GetActiveParseErrors[keyof GetActiveParseErrors];

export type GetActiveParseResponses = {
    /**
     * Current parse run-state.
     */
    200: ActiveParse;
};

export type GetActiveParseResponse = GetActiveParseResponses[keyof GetActiveParseResponses];

export type GetPendingScreenshotCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/screenshots/pending-count';
};

export type GetPendingScreenshotCountErrors = {
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type GetPendingScreenshotCountError = GetPendingScreenshotCountErrors[keyof GetPendingScreenshotCountErrors];

export type GetPendingScreenshotCountResponses = {
    /**
     * Count.
     */
    200: {
        count: number;
    };
};

export type GetPendingScreenshotCountResponse = GetPendingScreenshotCountResponses[keyof GetPendingScreenshotCountResponses];

export type UnignoreScreenshotData = {
    body?: never;
    path: {
        /**
         * Screenshot filename to suppress or un-suppress. URL-encoded
         * (the filename can contain spaces and dashes from the
         * Overwatch capture format).
         *
         */
        filename: string;
    };
    query?: never;
    url: '/api/v1/screenshots/{filename}/ignore';
};

export type UnignoreScreenshotErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type UnignoreScreenshotError = UnignoreScreenshotErrors[keyof UnignoreScreenshotErrors];

export type UnignoreScreenshotResponses = {
    /**
     * Filename removed from the ignore-list.
     */
    204: void;
};

export type UnignoreScreenshotResponse = UnignoreScreenshotResponses[keyof UnignoreScreenshotResponses];

export type IgnoreScreenshotData = {
    body?: never;
    path: {
        /**
         * Screenshot filename to suppress or un-suppress. URL-encoded
         * (the filename can contain spaces and dashes from the
         * Overwatch capture format).
         *
         */
        filename: string;
    };
    query?: never;
    url: '/api/v1/screenshots/{filename}/ignore';
};

export type IgnoreScreenshotErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type IgnoreScreenshotError = IgnoreScreenshotErrors[keyof IgnoreScreenshotErrors];

export type IgnoreScreenshotResponses = {
    /**
     * Filename added to the ignore-list.
     */
    204: void;
};

export type IgnoreScreenshotResponse = IgnoreScreenshotResponses[keyof IgnoreScreenshotResponses];

export type ClearIgnoredScreenshotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/screenshots/ignored';
};

export type ClearIgnoredScreenshotsErrors = {
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type ClearIgnoredScreenshotsError = ClearIgnoredScreenshotsErrors[keyof ClearIgnoredScreenshotsErrors];

export type ClearIgnoredScreenshotsResponses = {
    /**
     * Suppress list cleared.
     */
    204: void;
};

export type ClearIgnoredScreenshotsResponse = ClearIgnoredScreenshotsResponses[keyof ClearIgnoredScreenshotsResponses];

export type GetIgnoredScreenshotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/screenshots/ignored';
};

export type GetIgnoredScreenshotsErrors = {
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type GetIgnoredScreenshotsError = GetIgnoredScreenshotsErrors[keyof GetIgnoredScreenshotsErrors];

export type GetIgnoredScreenshotsResponses = {
    /**
     * List of ignored screenshots.
     */
    200: Array<IgnoredScreenshot>;
};

export type GetIgnoredScreenshotsResponse = GetIgnoredScreenshotsResponses[keyof GetIgnoredScreenshotsResponses];

export type GetFailedFilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/screenshots/failed';
};

export type GetFailedFilesErrors = {
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type GetFailedFilesError = GetFailedFilesErrors[keyof GetFailedFilesErrors];

export type GetFailedFilesResponses = {
    /**
     * List of failed files.
     */
    200: Array<FailedFile>;
};

export type GetFailedFilesResponse = GetFailedFilesResponses[keyof GetFailedFilesResponses];

export type ResetScreenshotsFolderData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/screenshots-folder';
};

export type ResetScreenshotsFolderErrors = {
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type ResetScreenshotsFolderError = ResetScreenshotsFolderErrors[keyof ResetScreenshotsFolderErrors];

export type ResetScreenshotsFolderResponses = {
    /**
     * Cleared.
     */
    204: void;
};

export type ResetScreenshotsFolderResponse = ResetScreenshotsFolderResponses[keyof ResetScreenshotsFolderResponses];

export type GetScreenshotsFolderData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/screenshots-folder';
};

export type GetScreenshotsFolderResponses = {
    /**
     * Current path.
     */
    200: FolderPath;
};

export type GetScreenshotsFolderResponse = GetScreenshotsFolderResponses[keyof GetScreenshotsFolderResponses];

export type SetScreenshotsFolderData = {
    body: {
        path: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/settings/screenshots-folder';
};

export type SetScreenshotsFolderErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * The request was syntactically valid, but the resource state or
     * a payload value prevents the action (e.g. duplicate profile
     * name, screenshots directory not configured, invalid Tesseract
     * binary path, non-candidate resolution target).
     *
     */
    409: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type SetScreenshotsFolderError = SetScreenshotsFolderErrors[keyof SetScreenshotsFolderErrors];

export type SetScreenshotsFolderResponses = {
    /**
     * New path echoed back.
     */
    200: FolderPath;
};

export type SetScreenshotsFolderResponse = SetScreenshotsFolderResponses[keyof SetScreenshotsFolderResponses];

export type ResetTesseractPathData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/tesseract';
};

export type ResetTesseractPathErrors = {
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type ResetTesseractPathError = ResetTesseractPathErrors[keyof ResetTesseractPathErrors];

export type ResetTesseractPathResponses = {
    /**
     * Re-detected status against the default path.
     */
    200: TesseractStatus;
};

export type ResetTesseractPathResponse = ResetTesseractPathResponses[keyof ResetTesseractPathResponses];

export type GetTesseractSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/tesseract';
};

export type GetTesseractSettingsResponses = {
    /**
     * Current engine status.
     */
    200: TesseractStatus;
};

export type GetTesseractSettingsResponse = GetTesseractSettingsResponses[keyof GetTesseractSettingsResponses];

export type SetTesseractPathData = {
    body: {
        path: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/settings/tesseract';
};

export type SetTesseractPathErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * The request was syntactically valid, but the resource state or
     * a payload value prevents the action (e.g. duplicate profile
     * name, screenshots directory not configured, invalid Tesseract
     * binary path, non-candidate resolution target).
     *
     */
    409: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type SetTesseractPathError = SetTesseractPathErrors[keyof SetTesseractPathErrors];

export type SetTesseractPathResponses = {
    /**
     * Re-detected status.
     */
    200: TesseractStatus;
};

export type SetTesseractPathResponse = SetTesseractPathResponses[keyof SetTesseractPathResponses];

export type GetWatchEnabledData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/watcher';
};

export type GetWatchEnabledResponses = {
    /**
     * Current state.
     */
    200: EnabledFlag;
};

export type GetWatchEnabledResponse = GetWatchEnabledResponses[keyof GetWatchEnabledResponses];

export type SetWatchEnabledData = {
    body: EnabledFlag;
    path?: never;
    query?: never;
    url: '/api/v1/settings/watcher';
};

export type SetWatchEnabledErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type SetWatchEnabledError = SetWatchEnabledErrors[keyof SetWatchEnabledErrors];

export type SetWatchEnabledResponses = {
    /**
     * Toggle applied.
     */
    204: void;
};

export type SetWatchEnabledResponse = SetWatchEnabledResponses[keyof SetWatchEnabledResponses];

export type GetExitOnCloseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/close-behavior';
};

export type GetExitOnCloseResponses = {
    /**
     * Current state.
     */
    200: CloseBehaviorFlag;
};

export type GetExitOnCloseResponse = GetExitOnCloseResponses[keyof GetExitOnCloseResponses];

export type SetExitOnCloseData = {
    body: CloseBehaviorFlag;
    path?: never;
    query?: never;
    url: '/api/v1/settings/close-behavior';
};

export type SetExitOnCloseErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type SetExitOnCloseError = SetExitOnCloseErrors[keyof SetExitOnCloseErrors];

export type SetExitOnCloseResponses = {
    /**
     * Preference saved.
     */
    204: void;
};

export type SetExitOnCloseResponse = SetExitOnCloseResponses[keyof SetExitOnCloseResponses];

export type GetAutoBackupStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings/auto-backup';
};

export type GetAutoBackupStatusResponses = {
    /**
     * Current schedule + newest-snapshot status.
     */
    200: AutoBackupStatus;
};

export type GetAutoBackupStatusResponse = GetAutoBackupStatusResponses[keyof GetAutoBackupStatusResponses];

export type SetAutoBackupIntervalData = {
    body: {
        /**
         * -1 disables, 0 resets to the default (weekly), else literal days.
         */
        interval_days: number;
    };
    path?: never;
    query?: never;
    url: '/api/v1/settings/auto-backup';
};

export type SetAutoBackupIntervalErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type SetAutoBackupIntervalError = SetAutoBackupIntervalErrors[keyof SetAutoBackupIntervalErrors];

export type SetAutoBackupIntervalResponses = {
    /**
     * Saved; refreshed status echoed.
     */
    200: AutoBackupStatus;
};

export type SetAutoBackupIntervalResponse = SetAutoBackupIntervalResponses[keyof SetAutoBackupIntervalResponses];

export type GetProfilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/profiles';
};

export type GetProfilesErrors = {
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type GetProfilesError = GetProfilesErrors[keyof GetProfilesErrors];

export type GetProfilesResponses = {
    /**
     * Active + list.
     */
    200: ProfilesResponse;
};

export type GetProfilesResponse = GetProfilesResponses[keyof GetProfilesResponses];

export type CreateProfileData = {
    body: {
        /**
         * Profile name. Filesystem-safe.
         *
         */
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/profiles';
};

export type CreateProfileErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * The request was syntactically valid, but the resource state or
     * a payload value prevents the action (e.g. duplicate profile
     * name, screenshots directory not configured, invalid Tesseract
     * binary path, non-candidate resolution target).
     *
     */
    409: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type CreateProfileError = CreateProfileErrors[keyof CreateProfileErrors];

export type CreateProfileResponses = {
    /**
     * Created and activated.
     */
    201: ProfilesResponse;
};

export type CreateProfileResponse = CreateProfileResponses[keyof CreateProfileResponses];

export type SeedTestProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/profiles/test/seed';
};

export type SeedTestProfileErrors = {
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type SeedTestProfileError = SeedTestProfileErrors[keyof SeedTestProfileErrors];

export type SeedTestProfileResponses = {
    /**
     * The sample profile is seeded (or was already).
     */
    200: SeedTestProfileResponse;
};

export type SeedTestProfileResponse2 = SeedTestProfileResponses[keyof SeedTestProfileResponses];

export type SwitchProfileData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/profiles/active';
};

export type SwitchProfileErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * The requested resource was not found.
     */
    404: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type SwitchProfileError = SwitchProfileErrors[keyof SwitchProfileErrors];

export type SwitchProfileResponses = {
    /**
     * Switched.
     */
    200: ProfilesResponse;
};

export type SwitchProfileResponse = SwitchProfileResponses[keyof SwitchProfileResponses];

export type DeleteProfileData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/profiles/{name}';
};

export type DeleteProfileErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * The requested resource was not found.
     */
    404: ProblemDetails;
    /**
     * Profile is active; switch away first.
     */
    409: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type DeleteProfileError = DeleteProfileErrors[keyof DeleteProfileErrors];

export type DeleteProfileResponses = {
    /**
     * Deleted.
     */
    204: void;
};

export type DeleteProfileResponse = DeleteProfileResponses[keyof DeleteProfileResponses];

export type RenameProfileData = {
    body: {
        /**
         * New profile name. Same regex as creation:
         * `^[a-zA-Z0-9][a-zA-Z0-9_-]{0,39}$`.
         *
         */
        new_name: string;
    };
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/profiles/{name}';
};

export type RenameProfileErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * The requested resource was not found.
     */
    404: ProblemDetails;
    /**
     * A profile with that new name already exists.
     */
    409: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type RenameProfileError = RenameProfileErrors[keyof RenameProfileErrors];

export type RenameProfileResponses = {
    /**
     * Renamed.
     */
    200: ProfilesResponse;
};

export type RenameProfileResponse = RenameProfileResponses[keyof RenameProfileResponses];

export type MoveMatchesData = {
    body: {
        match_keys: Array<string>;
        target_profile: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/matches/transfers';
};

export type MoveMatchesErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * The requested resource was not found.
     */
    404: ProblemDetails;
    /**
     * target_profile is the active profile.
     */
    409: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type MoveMatchesError = MoveMatchesErrors[keyof MoveMatchesErrors];

export type MoveMatchesResponses = {
    /**
     * Move complete.
     */
    204: void;
};

export type MoveMatchesResponse = MoveMatchesResponses[keyof MoveMatchesResponses];

export type GetStartupErrorData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/startup-error';
};

export type GetStartupErrorResponses = {
    /**
     * Captured startup error message (empty on clean boot).
     */
    200: {
        /**
         * Empty when Startup completed without capturing an
         * error; otherwise the wrapped failure string in
         * the format `startup: <stage>: <inner>`.
         *
         */
        message: string;
    };
};

export type GetStartupErrorResponse = GetStartupErrorResponses[keyof GetStartupErrorResponses];

export type GetVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/version';
};

export type GetVersionResponses = {
    /**
     * Current build version.
     */
    200: {
        version: string;
    };
};

export type GetVersionResponse = GetVersionResponses[keyof GetVersionResponses];

export type CheckForUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/update';
};

export type CheckForUpdateResponses = {
    /**
     * Update availability info.
     */
    200: UpdateInfo;
};

export type CheckForUpdateResponse = CheckForUpdateResponses[keyof CheckForUpdateResponses];

export type ApplyGameDataUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/data-update';
};

export type ApplyGameDataUpdateErrors = {
    /**
     * SHA-256 sidecar verification failed on at least one asset.
     * Nothing was written to disk. Returned by endpoints that
     * atomically apply downloaded reference data (e.g.
     * `POST /api/v1/system/data-update`) when the bytes received
     * don't match the published sidecar. The failing asset(s) are
     * listed in the problem's `failed_assets` extension member.
     *
     */
    422: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
    /**
     * An upstream fetch failed — e.g. the Pages-published data-update
     * channel is unreachable. No server state was modified.
     *
     */
    502: ProblemDetails;
};

export type ApplyGameDataUpdateError = ApplyGameDataUpdateErrors[keyof ApplyGameDataUpdateErrors];

export type ApplyGameDataUpdateResponses = {
    /**
     * Update applied; diff of what changed.
     */
    200: DataUpdateResult;
};

export type ApplyGameDataUpdateResponse = ApplyGameDataUpdateResponses[keyof ApplyGameDataUpdateResponses];

export type StartSelfUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/self-update';
};

export type StartSelfUpdateErrors = {
    /**
     * The request was syntactically valid, but the resource state or
     * a payload value prevents the action (e.g. duplicate profile
     * name, screenshots directory not configured, invalid Tesseract
     * binary path, non-candidate resolution target).
     *
     */
    409: ProblemDetails;
};

export type StartSelfUpdateError = StartSelfUpdateErrors[keyof StartSelfUpdateErrors];

export type StartSelfUpdateResponses = {
    /**
     * Self-update started.
     */
    202: unknown;
};

export type RestartToApplyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/self-update/restart';
};

export type RestartToApplyErrors = {
    /**
     * The request was syntactically valid, but the resource state or
     * a payload value prevents the action (e.g. duplicate profile
     * name, screenshots directory not configured, invalid Tesseract
     * binary path, non-candidate resolution target).
     *
     */
    409: ProblemDetails;
};

export type RestartToApplyError = RestartToApplyErrors[keyof RestartToApplyErrors];

export type RestartToApplyResponses = {
    /**
     * Restart accepted; the app is swapping + relaunching.
     */
    202: unknown;
};

export type GetDataLocationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/data-location';
};

export type GetDataLocationResponses = {
    /**
     * Path inventory.
     */
    200: DataLocation;
};

export type GetDataLocationResponse = GetDataLocationResponses[keyof GetDataLocationResponses];

export type GetReferenceDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/reference-data';
};

export type GetReferenceDataResponses = {
    /**
     * The embedded OW reference data.
     */
    200: {
        /**
         * Hero names grouped by role, alphabetised within each role.
         */
        heroes_by_role: {
            [key: string]: Array<string>;
        };
        /**
         * Map names grouped by game mode, alphabetised within each.
         */
        maps_by_game_mode: {
            [key: string]: Array<string>;
        };
        /**
         * Per-capture-tool filename grammars the parser
         * recognises. Source-of-truth is
         * `pkg/parser/screenshot_sources.yaml`. Surfaced
         * in Settings → Advanced → "Supported capture-
         * source rules" so the user can verify which
         * filename shapes work without leaving the app.
         *
         */
        screenshot_sources: Array<{
            /**
             * Stable id (nvidia / prntscn / snip / …).
             */
            name: string;
            /**
             * Fast strings.HasPrefix gate.
             */
            prefix: string;
            /**
             * Anchored Go regex; six capture groups (y, m, d, H, M, S).
             */
            regex: string;
            /**
             * Added to the captured year (2-digit YAML → 2000).
             */
            year_offset: number;
            /**
             * Canonical example filename.
             */
            example: string;
        }>;
        /**
         * Competitive season windows. Source-of-truth is
         * `pkg/parser/seasons.yaml`. Drives the season filter
         * (a match belongs to the season its START falls in)
         * and future season comparison. Boundaries are UTC.
         *
         */
        seasons: Array<{
            /**
             * Full season name, e.g. 'Reign of Talon — Season 2'.
             */
            name: string;
            /**
             * Grouping label, e.g. 'Reign of Talon'.
             */
            chapter: string;
            /**
             * Season number within the chapter.
             */
            number: number;
            /**
             * Season start, UTC RFC 3339 (inclusive).
             */
            start: string;
            /**
             * Season end, UTC RFC 3339 (exclusive; = next start).
             */
            end: string;
        }>;
    };
};

export type GetReferenceDataResponse = GetReferenceDataResponses[keyof GetReferenceDataResponses];

export type GetScreenshotsFolderCandidatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/screenshots-folder-candidates';
};

export type GetScreenshotsFolderCandidatesResponses = {
    /**
     * Per-source candidate list. Empty array on non-Windows
     * platforms.
     *
     */
    200: Array<NamedCandidate>;
};

export type GetScreenshotsFolderCandidatesResponse = GetScreenshotsFolderCandidatesResponses[keyof GetScreenshotsFolderCandidatesResponses];

export type GetScreenshotsFolderCandidateStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/screenshots-folder-candidates/stats';
};

export type GetScreenshotsFolderCandidateStatsResponses = {
    /**
     * Per-source stats list. Empty array on non-Windows
     * platforms. Each entry's `last_modified` is empty when
     * the source folder has no regular files.
     *
     */
    200: Array<{
        /**
         * Stable source id — matches the candidates endpoint.
         */
        name: string;
        /**
         * Regular files in the source dir, bounded to 1000.
         */
        file_count: number;
        /**
         * RFC3339 UTC of the most-recent write. Empty when no files.
         */
        last_modified: string;
        /**
         * Subset of file_count whose name matches one of the parser's filename grammars.
         */
        recognised_count: number;
    }>;
};

export type GetScreenshotsFolderCandidateStatsResponse = GetScreenshotsFolderCandidateStatsResponses[keyof GetScreenshotsFolderCandidateStatsResponses];

export type ProbeTesseractBinaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/tesseract-probe';
};

export type ProbeTesseractBinaryResponses = {
    /**
     * Probe result. `found: true` carries the discovered path;
     * `found: false` includes the full `tried` list for the
     * user to inspect.
     *
     */
    200: ProbeResult;
};

export type ProbeTesseractBinaryResponse = ProbeTesseractBinaryResponses[keyof ProbeTesseractBinaryResponses];

export type RevealScreenshotsFolderData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/screenshots-folder-reveal';
};

export type RevealScreenshotsFolderErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * The request was syntactically valid, but the resource state or
     * a payload value prevents the action (e.g. duplicate profile
     * name, screenshots directory not configured, invalid Tesseract
     * binary path, non-candidate resolution target).
     *
     */
    409: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type RevealScreenshotsFolderError = RevealScreenshotsFolderErrors[keyof RevealScreenshotsFolderErrors];

export type RevealScreenshotsFolderResponses = {
    /**
     * Opener spawned.
     */
    202: unknown;
};

export type BackupDatabaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/database';
};

export type BackupDatabaseErrors = {
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type BackupDatabaseError = BackupDatabaseErrors[keyof BackupDatabaseErrors];

export type BackupDatabaseResponses = {
    /**
     * A SQLite database file.
     */
    200: Blob | File;
};

export type BackupDatabaseResponse = BackupDatabaseResponses[keyof BackupDatabaseResponses];

export type RestoreDatabaseData = {
    /**
     * A SQLite database file produced by `GET /api/v1/database`.
     */
    body: Blob | File;
    path?: never;
    query?: never;
    url: '/api/v1/database';
};

export type RestoreDatabaseErrors = {
    /**
     * A parse is in flight; retry once it completes.
     */
    409: ProblemDetails;
    /**
     * The uploaded file is not a usable Recall database.
     */
    422: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type RestoreDatabaseError = RestoreDatabaseErrors[keyof RestoreDatabaseErrors];

export type RestoreDatabaseResponses = {
    /**
     * Database restored.
     */
    204: void;
};

export type RestoreDatabaseResponse = RestoreDatabaseResponses[keyof RestoreDatabaseResponses];

export type GetDatabaseHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/database/health';
};

export type GetDatabaseHealthErrors = {
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type GetDatabaseHealthError = GetDatabaseHealthErrors[keyof GetDatabaseHealthErrors];

export type GetDatabaseHealthResponses = {
    /**
     * Point-in-time health report.
     */
    200: DbHealth;
};

export type GetDatabaseHealthResponse = GetDatabaseHealthResponses[keyof GetDatabaseHealthResponses];

export type RunDatabaseMaintenanceData = {
    body: {
        operation: 'optimize' | 'vacuum';
    };
    path?: never;
    query?: never;
    url: '/api/v1/database/maintenance';
};

export type RunDatabaseMaintenanceErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * A parse is in flight; retry once it completes.
     */
    409: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type RunDatabaseMaintenanceError = RunDatabaseMaintenanceErrors[keyof RunDatabaseMaintenanceErrors];

export type RunDatabaseMaintenanceResponses = {
    /**
     * Operation completed; refreshed health report.
     */
    200: DbHealth;
};

export type RunDatabaseMaintenanceResponse = RunDatabaseMaintenanceResponses[keyof RunDatabaseMaintenanceResponses];

export type ExportBundleData = {
    body: {
        /**
         * Explicit list of match_keys to include in the
         * bundle. Empty array combined with
         * `include_unknown=false` and
         * `include_hidden=false` produces an empty
         * bundle (manifest with `match_count: 0`).
         *
         */
        match_keys: Array<string>;
        /**
         * Add every record whose `data.map` is empty (the
         * Matches view's "unknown" filter).
         *
         */
        include_unknown?: boolean;
        /**
         * Add every record currently in `hidden_matches`.
         *
         */
        include_hidden?: boolean;
    };
    path?: never;
    query?: never;
    url: '/api/v1/exports/bundle';
};

export type ExportBundleErrors = {
    /**
     * Malformed request body or query parameters.
     */
    400: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type ExportBundleError = ExportBundleErrors[keyof ExportBundleErrors];

export type ExportBundleResponses = {
    /**
     * ZIP bundle with a `Content-Disposition: attachment;
     * filename="recall-bundle-<timestamp>.zip"` header.
     *
     */
    200: Blob | File;
};

export type ExportBundleResponse = ExportBundleResponses[keyof ExportBundleResponses];

export type ExportDiagnosticBundleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/exports/diagnostic';
};

export type ExportDiagnosticBundleErrors = {
    /**
     * The request was syntactically valid, but the resource state or
     * a payload value prevents the action (e.g. duplicate profile
     * name, screenshots directory not configured, invalid Tesseract
     * binary path, non-candidate resolution target).
     *
     */
    409: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type ExportDiagnosticBundleError = ExportDiagnosticBundleErrors[keyof ExportDiagnosticBundleErrors];

export type ExportDiagnosticBundleResponses = {
    /**
     * ZIP bundle with a `Content-Disposition: attachment;
     * filename="recall-diagnostic-<timestamp>.zip"` header.
     *
     */
    200: Blob | File;
};

export type ExportDiagnosticBundleResponse = ExportDiagnosticBundleResponses[keyof ExportDiagnosticBundleResponses];

export type ImportMatchesData = {
    /**
     * A recall-bundle/v1 ZIP from POST /api/v1/exports/bundle.
     */
    body: Blob | File;
    path?: never;
    query?: never;
    url: '/api/v1/imports';
};

export type ImportMatchesErrors = {
    /**
     * Payload was not a readable Recall bundle (not a ZIP, archive
     * open failure, missing or undecodable manifest/data.json).
     *
     */
    400: ProblemDetails;
    /**
     * The bundle was readable but its schema is unsupported by this
     * build.
     *
     */
    409: ProblemDetails;
    /**
     * Unhandled server-side error.
     */
    500: ProblemDetails;
};

export type ImportMatchesError = ImportMatchesErrors[keyof ImportMatchesErrors];

export type ImportMatchesResponses = {
    /**
     * Merge applied; counts of added vs skipped matches.
     */
    200: ImportSummary;
};

export type ImportMatchesResponse = ImportMatchesResponses[keyof ImportMatchesResponses];

export type EventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/events';
};

export type EventsResponses = {
    /**
     * SSE stream.
     */
    200: string;
};

export type EventsResponse = EventsResponses[keyof EventsResponses];

export type GetScreenshotData = {
    body?: never;
    path: {
        /**
         * screenshots_dirs row id the file lives under; 0 means the currently configured screenshots folder.
         */
        dir_id: number;
        /**
         * URL-encoded basename of a file in the screenshots folder.
         */
        filename: string;
    };
    query?: never;
    url: '/_screenshot/{dir_id}/{filename}';
};

export type GetScreenshotErrors = {
    /**
     * Malformed path or filename.
     */
    400: unknown;
    /**
     * File not found, no folder configured, or path traversal rejected.
     */
    404: unknown;
};

export type GetScreenshotResponses = {
    /**
     * Image bytes.
     */
    200: Blob | File;
};

export type GetScreenshotResponse = GetScreenshotResponses[keyof GetScreenshotResponses];
