// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['app']['App']['CheckForUpdate']();
}

export function ClearDatabase() {
  return window['go']['app']['App']['ClearDatabase']();
}

export function GetMatchResults() {
  return window['go']['app']['App']['GetMatchResults']();
}

export function GetNewScreenshotCount() {
  return window['go']['app']['App']['GetNewScreenshotCount']();
}

export function GetPrometheusEnabled() {
  return window['go']['app']['App']['GetPrometheusEnabled']();
}

export function GetScreenshotsDir() {
  return window['go']['app']['App']['GetScreenshotsDir']();
}

export function GetTesseractStatus() {
  return window['go']['app']['App']['GetTesseractStatus']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function GetWatchEnabled() {
  return window['go']['app']['App']['GetWatchEnabled']();
}

export function ParseScreenshots() {
  return window['go']['app']['App']['ParseScreenshots']();
}

export function PickScreenshotsDir() {
  return window['go']['app']['App']['PickScreenshotsDir']();
}

export function PickTesseractBinary() {
  return window['go']['app']['App']['PickTesseractBinary']();
}

export function ResetTesseractPath() {
  return window['go']['app']['App']['ResetTesseractPath']();
}

export function ScreenshotHandler() {
  return window['go']['app']['App']['ScreenshotHandler']();
}

export function SetPrometheusEnabled(arg1) {
  return window['go']['app']['App']['SetPrometheusEnabled'](arg1);
}

export function SetScreenshotsDir(arg1) {
  return window['go']['app']['App']['SetScreenshotsDir'](arg1);
}

export function SetTesseractPath(arg1) {
  return window['go']['app']['App']['SetTesseractPath'](arg1);
}

export function SetWatchEnabled(arg1) {
  return window['go']['app']['App']['SetWatchEnabled'](arg1);
}
