/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/match-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all parsed match records
         * @description Returns every row from the SQLite `match_results` table, in
         *     insertion order. Read-time derivations (`inferSoleHeroPercent`,
         *     `inferResultFromRank`) are already applied to each record.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of match records. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchRecord"][];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screenshots-dir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the configured screenshots folder
         * @description Returns the path Recall is currently reading from. Can be
         *     absolute (e.g. `/Users/.../Overwatch/ScreenShots/Overwatch`) or
         *     relative to the server's working directory.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current path. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example screenshots */
                            path: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Set the screenshots folder
         * @description Persists to `settings.json` and re-targets the file watcher if
         *     it's armed. Path can be absolute or relative to the server's
         *     working directory.
         *
         *     Validation (400 on failure):
         *     - Only filesystem-safe characters (alphanumerics, `_ . / \ : - <space>
         *       ( ) + ' ,`). Shell metacharacters, NUL bytes, and control codes
         *       are rejected.
         *     - Must be in canonical form — `filepath.Clean(path) == path`
         *       (no redundant slashes or `..` traversal segments).
         *     - Must point at an existing directory.
         *
         *     The echoed-back `path` is the cleaned form actually stored.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example /Users/jacob/Documents/Overwatch/ScreenShots/Overwatch */
                        path: string;
                    };
                };
            };
            responses: {
                /** @description New path echoed back. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            path: string;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a one-shot parse
         * @description Walks the configured screenshots folder, OCRs anything not
         *     already in the DB, and writes the merged rows. Idempotent —
         *     re-running won't duplicate matches already on record.
         *     Synchronous: the response only returns after parsing finishes.
         *     Progress is also broadcast via the SSE endpoint.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prometheus-enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the Prometheus metrics-endpoint toggle
         * @description `true` iff the `:9091/metrics` listener is currently bound and
         *     the Prometheus collector is registered.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current state. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnabledFlag"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Toggle the Prometheus metrics endpoint
         * @description Enabling binds `:9091/metrics` (override via
         *     `OWMETRICS_METRICS_ADDR`). Disabling shuts the listener down
         *     with a 2s grace period.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EnabledFlag"];
                };
            };
            responses: {
                /** @description New state echoed back. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnabledFlag"];
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch-enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the file-watcher toggle
         * @description `true` iff the fsnotify watcher is armed against the configured
         *     screenshots folder.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current state. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnabledFlag"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Toggle the file watcher
         * @description When on, new `.png` / `.jpg` files in the configured folder are
         *     auto-parsed after a 60s debounce. Requires a working Tesseract
         *     binary — turning it on without one returns 500.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EnabledFlag"];
                };
            };
            responses: {
                /** @description New state echoed back. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnabledFlag"];
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tesseract-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the OCR engine status
         * @description Reports the configured Tesseract path, whether it resolves to a
         *     working binary, the reported version, the platform default
         *     path, and any error from the last detection attempt.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current engine status. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TesseractStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tesseract-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set the Tesseract binary path
         * @description Re-runs detection on the new path. The status returned reflects
         *     whether the binary at that path responds to `--version`.
         *
         *     Validation (400 on failure — the path is rejected before
         *     `exec.Command` is invoked, so a malformed path never reaches a
         *     syscall):
         *     - Only filesystem-safe characters (alphanumerics, `_ . / \ : - <space>
         *       ( ) + ' ,`). Shell metacharacters, NUL bytes, and control codes
         *       are rejected.
         *     - Must be in canonical form — `filepath.Clean(path) == path`.
         *     - Must be an absolute path.
         *     - Basename must be exactly `tesseract` or `tesseract.exe` — this
         *       pins the endpoint to "swap which Tesseract is used" and
         *       forbids using it to launch arbitrary binaries.
         *
         *     `POST /api/tesseract-reset` bypasses this validation because the
         *     platform default (`defaultTesseractPath()`) is trusted.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example /opt/homebrew/bin/tesseract */
                        path: string;
                    };
                };
            };
            responses: {
                /** @description Re-detected status. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TesseractStatus"];
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tesseract-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset the Tesseract path to the platform default
         * @description Replaces the configured path with the platform default (Homebrew
         *     on macOS, `/usr/bin/tesseract` on Linux, the Windows installer
         *     path on Windows) and re-runs detection.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Re-detected status against the default path. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TesseractStatus"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App build version
         * @description Returns the version string injected at build time via
         *     `-ldflags "-X recall/pkg/app.Version=<tag>"`.
         *     Falls back to `"dev"` for local builds outside the release pipeline.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current build version. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0.0.13-beta.0 */
                            version: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/new-screenshot-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count of new screenshots awaiting parse
         * @description Returns the number of files in the configured folder that are
         *     not yet present in any `match_results` row's `source_files`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Count. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 3 */
                            count: number;
                        };
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clear-database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Wipe all parsed match records
         * @description Deletes every row from `match_results`. Settings and the
         *     screenshots folder are untouched; you can re-parse to rebuild.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream
         * @description Long-lived `text/event-stream` connection. Subscribers receive:
         *       * `parse-progress` — fired per OCR'd file during a parse run,
         *         carries `{done, total, filename, screenshot_type, data?}`
         *       * `parse-complete` — fired after a parse run finishes
         *       * Keepalive comment lines every 25 s so reverse proxies
         *         don't close the connection
         *
         *     Clients should reconnect on disconnect; messages are not
         *     replayed.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_screenshot/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve a screenshot image from the configured folder
         * @description Streams a file from the configured screenshots directory. The
         *     `{filename}` parameter must be a plain basename; path traversal
         *     (`..`, `/`, `\`) is rejected. Used by the frontend to render
         *     `<img>` previews without round-tripping bytes through the JSON
         *     bridge.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description URL-encoded basename of a file in the screenshots folder.
                     * @example Overwatch%202%20Screenshot%202026.05.10%20-%2021.49.34.41.png
                     */
                    filename: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Image bytes. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                        "image/jpeg": string;
                    };
                };
                /** @description Malformed path or filename. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description File not found, no folder configured, or path traversal rejected. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One DB row — the merged result of one or more screenshots. */
        MatchRecord: {
            /**
             * Format: int64
             * @example 24
             */
            id: number;
            /**
             * @description Stable identity. Either `match:<ISO-timestamp>` (from the
             *     earliest screenshot's filename) or `unmatched:<filename>` for
             *     files whose names didn't parse as timestamps.
             * @example match:2026-05-10T22:21:11
             */
            match_key: string;
            /**
             * @description Every screenshot filename that fed this match.
             * @example [
             *       "Overwatch Screenshot 2026.05.10 - 22.21.11.79.png",
             *       "Overwatch Screenshot 2026.05.10 - 22.21.57.34.png"
             *     ]
             */
            source_files: string[];
            /**
             * @description Per-source-file screenshot classification. Populated at
             *     parse time. May be absent on rows parsed before this column
             *     landed.
             * @example {
             *       "Overwatch Screenshot 2026.05.10 - 22.21.11.79.png": "scoreboard",
             *       "Overwatch Screenshot 2026.05.10 - 22.21.57.34.png": "rank"
             *     }
             */
            source_types?: {
                [key: string]: components["schemas"]["ScreenshotType"];
            };
            data: components["schemas"]["MatchResult"];
        };
        /**
         * @description Classification of one screenshot:
         *       * `summary` — post-match SUMMARY tab
         *       * `scoreboard` — in-game or post-match TEAMS scoreboard
         *       * `personal` — post-match PERSONAL tab
         *       * `rank` — competitive RANK PROGRESS screen
         * @enum {string}
         */
        ScreenshotType: "summary" | "scoreboard" | "personal" | "rank";
        /** @description All parsed data for a match, merged across its source files. */
        MatchResult: {
            /** @description e.g. "rialto" */
            map?: string;
            /** @description e.g. "control" */
            type?: string;
            /** @enum {string} */
            mode?: "competitive" | "quickplay" | "unranked" | "";
            /** @enum {string} */
            role?: "tank" | "dps" | "support" | "";
            /** @description Primary (most-played) hero */
            hero?: string;
            eliminations?: number;
            assists?: number;
            deaths?: number;
            damage?: number;
            healing?: number;
            mitigation?: number;
            /** @enum {string} */
            result?: "victory" | "defeat" | "draw" | "";
            /** @example 3-1 */
            final_score?: string;
            /** @example 2026-05-10 */
            date?: string;
            /**
             * @description HH:MM 24h as shown by the OW client.
             * @example 21:29
             */
            finished_at?: string;
            /** @example 11:25 */
            game_length?: string;
            heroes_played?: components["schemas"]["HeroPlay"][];
            performance?: components["schemas"]["Performance"];
            /** @example platinum */
            rank?: string;
            level?: number;
            /**
             * @example [
             *       "expected",
             *       "victory"
             *     ]
             */
            modifiers?: string[];
            rank_progress?: number;
            /** @description Percentage the rank moved this match (signed). */
            change_percent?: number;
            sr?: components["schemas"]["HeroSR"][];
        };
        HeroPlay: {
            /** @example lucio */
            hero: string;
            /** @example 100 */
            percent_played: number;
            /** @example 11:25 */
            play_time?: string;
            /**
             * @description Hero-specific stats keyed by snake_case label.
             * @example {
             *       "weapon_accuracy": 24,
             *       "players_saved": 6
             *     }
             */
            stats?: {
                [key: string]: number;
            };
        };
        HeroSR: {
            /** @example lucio */
            hero: string;
            /** @example 2754 */
            sr: number;
            /**
             * @description Signed delta this match
             * @example 30
             */
            change: number;
        };
        Performance: {
            eliminations?: components["schemas"]["PerformanceStat"];
            assists?: components["schemas"]["PerformanceStat"];
            deaths?: components["schemas"]["PerformanceStat"];
        };
        PerformanceStat: {
            total: number;
            /** Format: double */
            avg_per_10min?: number;
        };
        TesseractStatus: {
            /**
             * @description The currently-configured path.
             * @example /opt/homebrew/bin/tesseract
             */
            path: string;
            /** @description True iff `path` resolves to a working binary. */
            found: boolean;
            /** @description Tesseract `--version` output (e.g. "5.4.1"). Empty when not found. */
            version: string;
            /** @description Description of the last detection failure, if any. */
            error: string;
            /** @description Platform default path (Homebrew on macOS, /usr/bin on Linux, etc.). */
            default: string;
        };
        EnabledFlag: {
            enabled: boolean;
        };
        Ok: {
            /** @enum {boolean} */
            ok: true;
        };
    };
    responses: {
        /** @description Success — `{ "ok": true }`. */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Ok"];
            };
        };
        /** @description Malformed request body or query parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Unhandled server-side error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
