/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all parsed match records
         * @description Returns one record per match, assembled by JOINing the
         *     per-screenshot-type rows (summary / scoreboard / personal /
         *     rank / unknown) that share each `match_key`. Read-time
         *     derivations (`inferSoleHeroPercent`, `inferResultFromRank`)
         *     plus role-from-hero and type-from-map lookups are applied
         *     on the fly — the underlying rows are never mutated.
         */
        get: operations["GetMatchResults"];
        put?: never;
        post?: never;
        /**
         * Wipe all parsed match records
         * @description Deletes every row from the per-screenshot tables (and their
         *     child rows via `ON DELETE CASCADE`). Settings and the
         *     screenshots folder are untouched; you can re-parse to rebuild.
         */
        delete: operations["ClearMatches"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{matchKey}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Match identity — same `match_key` exposed in `MatchRecord`.
                 *     URL-encoded because the value normally contains a colon
                 *     (e.g. `match:2026-05-10T22:21:11`).
                 * @example match%3A2026-05-10T22%3A21%3A11
                 */
                matchKey: components["parameters"]["MatchKey"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Hard-delete a single match
         * @description Removes every trace of the match from the database: rows
         *     across all five parent screenshot tables (children CASCADE),
         *     the `match_annotations` row, and the `hidden_matches` flag.
         *     Source PNG files on disk are NOT touched, but `LoadAllFilenames`
         *     will then re-classify them as new and the next parse will
         *     re-ingest. Surfaced by the Hidden drawer's **Delete forever**
         *     affordance — the user has already moved the match to the
         *     archive and explicitly confirmed.
         *
         *     Idempotent: unknown keys return 204.
         */
        delete: operations["HardDeleteMatch"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{matchKey}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Match identity — same `match_key` exposed in `MatchRecord`.
                 *     URL-encoded because the value normally contains a colon
                 *     (e.g. `match:2026-05-10T22:21:11`).
                 * @example match%3A2026-05-10T22%3A21%3A11
                 */
                matchKey: components["parameters"]["MatchKey"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Hide or unhide a match (soft delete)
         * @description Flips a match's hidden state. `hidden: true` records a
         *     soft-delete entry in the `hidden_matches` table; the
         *     aggregator then sets `MatchRecord.hidden = true` on every
         *     read and the default filter drops the match from the
         *     Matches list. The per-screenshot rows in the parent tables
         *     are untouched, so a re-parse of the same PNG files continues to
         *     skip them (`LoadAllFilenames` sees them as parsed).
         *
         *     `hidden: false` removes the soft-delete and the match
         *     re-appears. Both directions are idempotent — repeated
         *     identical calls succeed.
         */
        put: operations["SetMatchVisibility"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{matchKey}/resolution": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Match identity — same `match_key` exposed in `MatchRecord`.
                 *     URL-encoded because the value normally contains a colon
                 *     (e.g. `match:2026-05-10T22:21:11`).
                 * @example match%3A2026-05-10T22%3A21%3A11
                 */
                matchKey: components["parameters"]["MatchKey"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Resolve an ambiguous-attribution screenshot
         * @description When the resolver can't pin a screenshot to a single match
         *     (identical EAD signature within the 5-30 min ambiguous window,
         *     or multiple candidates within 30 min), the parent row's
         *     `match_key` is set to `ambiguous:<filename>` and the candidate
         *     list is recorded in `ambiguous_candidates`. Other screenshots
         *     captured within `mergeWindow` of that one adopt the same
         *     sentinel via the timestamp-window pass — so several rows can
         *     share one ambiguous `match_key`.
         *
         *     This endpoint rewrites every parent row carrying the given
         *     ambiguous key to `resolved_to`. `matchKey` must start with
         *     `ambiguous:` (anything else returns 400). `resolved_to` must
         *     either be one of the recorded candidates OR a freshly-minted
         *     `match:<...>` key (the "Treat as new match" escape hatch in
         *     the Unknown tab).
         *
         *     On success the ambiguous row + its candidates cascade-delete
         *     and a `match-updated` SSE event fires for the resolved key.
         */
        put: operations["ResolveAmbiguousMatch"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{matchKey}/annotation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Match identity — same `match_key` exposed in `MatchRecord`.
                 *     URL-encoded because the value normally contains a colon
                 *     (e.g. `match:2026-05-10T22:21:11`).
                 * @example match%3A2026-05-10T22%3A21%3A11
                 */
                matchKey: components["parameters"]["MatchKey"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Upsert or clear a per-match user annotation
         * @description Lets the user tag a match with up to four pieces of metadata:
         *
         *       - **leaver** — `self` (user left, data incomplete) /
         *         `team` (ally left, loss excused) / `enemy` (opponent left,
         *         win tainted). Drives W/L/D tally exclusion via the
         *         FilterRail leaver-handling setting.
         *       - **note** — free-text per-match commentary.
         *       - **replay_code** — Overwatch's six-character replay ID so
         *         the match can be re-watched in the in-game viewer.
         *       - **members** — BattleTags of group members; verbatim, no
         *         canonicalisation.
         *
         *     Every field is optional. If *every* field is empty (or the
         *     members array is empty) the request acts as a delete — the
         *     annotation row is removed entirely, cascading any member rows
         *     away. Idempotent — clearing a non-existent annotation
         *     succeeds.
         *
         *     Returns 204 on success, 400 on validation failure (`leaver`
         *     outside the enum), 500 on store error.
         */
        put: operations["SetMatchAnnotation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a one-shot parse
         * @description Walks the configured screenshots folder, OCRs anything not
         *     already in the DB, and writes the merged rows. Idempotent —
         *     re-running won't duplicate matches already on record.
         *
         *     Returns `202 Accepted` because the meaningful side-effect is
         *     the SQLite writes and SSE broadcast, not the HTTP response
         *     body. Subscribe to `GET /api/v1/events` for progress and
         *     re-fetch `GET /api/v1/matches` when done.
         *
         *     The handler is currently synchronous (the response holds until
         *     parsing finishes), but the 202 contract keeps callers from
         *     depending on that internal detail.
         */
        post: operations["ParseScreenshots"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screenshots/pending-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count of screenshots awaiting parse
         * @description Returns the number of files in the configured folder that are
         *     not yet present in any per-screenshot-type table's `filename`.
         */
        get: operations["GetPendingScreenshotCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/screenshots-folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the configured screenshots folder
         * @description Returns the path Recall is currently reading from. Can be
         *     absolute (e.g. `/Users/.../Overwatch/ScreenShots/Overwatch`) or
         *     relative to the server's working directory.
         */
        get: operations["GetScreenshotsFolder"];
        /**
         * Set the screenshots folder
         * @description Persists to `settings.json` and re-targets the file watcher if
         *     it's armed. Path can be absolute or relative to the server's
         *     working directory.
         *
         *     Validation (400 on failure):
         *     - Only filesystem-safe characters (alphanumerics, `_ . / \ : - <space>
         *       ( ) + ' ,`). Shell metacharacters, NUL bytes, and control codes
         *       are rejected.
         *     - Must be in canonical form — `filepath.Clean(path) == path`
         *       (no redundant slashes or `..` traversal segments).
         *     - Must point at an existing directory.
         *
         *     The echoed-back `path` is the cleaned form actually stored.
         */
        put: operations["SetScreenshotsFolder"];
        post?: never;
        /**
         * Clear the configured screenshots folder
         * @description Symmetric with `DELETE /api/v1/settings/tesseract` — the user-
         *     set override is the thing being deleted. There's no platform
         *     default to fall back to; the natural empty state is "no folder
         *     configured" and the user re-picks via Detect / Change.
         *
         *     Also tears down the file watcher if it was armed against the
         *     now-cleared path so we don't leak an fsnotify handle pointing
         *     at an orphaned dir.
         */
        delete: operations["ResetScreenshotsFolder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/tesseract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the OCR engine status
         * @description Reports the configured Tesseract path, whether it resolves to a
         *     working binary, the reported version, whether that version is
         *     officially supported (5.x only), the platform default path, and
         *     any error from the last detection attempt.
         *
         *     When `found` is true but `supported` is false (e.g. a 3.x or
         *     4.x binary), the UI shows a caution banner and prompts for
         *     confirmation before running a parse — results may be incorrect
         *     with unsupported versions.
         */
        get: operations["GetTesseractSettings"];
        /**
         * Set the Tesseract binary path
         * @description Re-runs detection on the new path. The status returned reflects
         *     whether the binary at that path responds to `--version`.
         *
         *     Validation (400 on failure — the path is rejected before
         *     `exec.Command` is invoked, so a malformed path never reaches a
         *     syscall):
         *     - Only filesystem-safe characters (alphanumerics, `_ . / \ : - <space>
         *       ( ) + ' ,`). Shell metacharacters, NUL bytes, and control codes
         *       are rejected.
         *     - Must be in canonical form — `filepath.Clean(path) == path`.
         *     - Must be an absolute path.
         *     - Basename must be exactly `tesseract` or `tesseract.exe` — this
         *       pins the endpoint to "swap which Tesseract is used" and
         *       forbids using it to launch arbitrary binaries.
         *
         *     `DELETE /api/v1/settings/tesseract` bypasses this validation
         *     because the platform default (`defaultTesseractPath()`) is
         *     trusted.
         */
        put: operations["SetTesseractPath"];
        post?: never;
        /**
         * Reset the Tesseract path to the platform default
         * @description Replaces the configured path with the platform default (Homebrew
         *     on macOS, `/usr/bin/tesseract` on Linux, the Windows installer
         *     path on Windows) and re-runs detection. Modeled as a DELETE
         *     because it removes the user-set override, returning the field
         *     to its implicit default.
         */
        delete: operations["ResetTesseractPath"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/prometheus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the Prometheus metrics-endpoint toggle
         * @description `true` iff the `:9091/metrics` listener is currently bound and
         *     the Prometheus collector is registered.
         */
        get: operations["GetPrometheusEnabled"];
        /**
         * Toggle the Prometheus metrics endpoint
         * @description Enabling binds `:9091/metrics` (override via
         *     `OWMETRICS_METRICS_ADDR`). Disabling shuts the listener down
         *     with a 2s grace period.
         */
        put: operations["SetPrometheusEnabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/watcher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the file-watcher toggle
         * @description `true` iff the fsnotify watcher is armed against the configured
         *     screenshots folder.
         */
        get: operations["GetWatchEnabled"];
        /**
         * Toggle the file watcher
         * @description When on, new `.png` / `.jpg` files in the configured folder are
         *     auto-parsed after a 60s debounce. Requires a working Tesseract
         *     binary — turning it on without one returns 500.
         */
        put: operations["SetWatchEnabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all known profiles and which is active
         * @description Each profile gets its own settings + SQLite DB under
         *     `<base>/profiles/<name>/`. The masthead switcher chip
         *     renders the list and highlights the active one.
         */
        get: operations["GetProfiles"];
        put?: never;
        /**
         * Create a new profile and activate it
         * @description Creates the profile directory, adds it to the list, and
         *     activates it in one shot. The app tears down the active store
         *     and re-initializes against the new profile's directory before
         *     the response returns — so callers can re-fetch all data
         *     immediately afterward (or window.location.reload() the SPA).
         */
        post: operations["CreateProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Switch the active profile
         * @description Tears down the App's in-memory state tied to the previous
         *     profile (settings, store, watcher, metrics endpoint) and
         *     re-initializes everything against the new profile's directory.
         *     The wire response carries the new state so the caller can update
         *     UI without a round-trip.
         */
        put: operations["SwitchProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Rename a profile
         * @description Renames the on-disk directory + updates `profiles.json`. If
         *     the renamed profile is the active one, the in-memory store is
         *     closed before the directory rename and re-opened against the
         *     new path so settings + DB carry through transparently. Returns
         *     the updated active + list.
         *
         *     Idempotent when `new_name == old`.
         */
        put: operations["RenameProfile"];
        post?: never;
        /**
         * Delete a non-active profile and wipe its directory
         * @description Removes the profile from the list AND removes its directory
         *     tree (including the SQLite DB + settings) from disk. The
         *     active profile cannot be deleted — callers must
         *     `PUT /api/v1/profiles/active` to a different profile first.
         */
        delete: operations["DeleteProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk move matches from the active profile to another profile
         * @description Transfers every row keyed on `match_keys` (across all 5 parent
         *     screenshot tables) + annotations + the `hidden_matches` flag
         *     from the active profile's DB into `target_profile`'s DB, then
         *     hard-deletes from the source. The target's `screenshots_dirs`
         *     id space is independent from the source's, so per-row
         *     `screenshots_dir_id` is re-resolved against the target by path.
         *
         *     Two-phase: target writes succeed first; source delete happens
         *     second. A retry on the same keys after a mid-transfer failure
         *     re-targets the already-moved rows (idempotent via
         *     `ON CONFLICT(filename)`) and completes the source delete.
         */
        post: operations["MoveMatches"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App build version
         * @description Returns the version string injected at build time via
         *     `-ldflags "-X recall/pkg/app.Version=<tag>"`.
         *     Falls back to `"dev"` for local builds outside the release pipeline.
         */
        get: operations["GetVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check for a newer release
         * @description Queries the GitHub releases API for the latest stable release and
         *     compares it against the running build version. Returns
         *     `available: false` when already up to date, running a dev build,
         *     or when the API is unreachable (network failures are silenced).
         */
        get: operations["CheckForUpdate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/data-location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report the on-disk paths used by this install
         * @description Surface the SQLite database path, settings file path, base
         *     data directory, and the currently-configured screenshots
         *     folder. Honors the `RECALL_DATA_DIR` env override (set in
         *     `.envrc` for `wails dev`), so the response matches what the
         *     running app actually reads/writes.
         */
        get: operations["GetDataLocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/reference-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overwatch reference data (hero roster + map roster)
         * @description Returns the static reference data baked into the parser at
         *     compile time from `pkg/parser/heroes.yaml` and
         *     `pkg/parser/maps.yaml`. Stable across an app session — the
         *     frontend may fetch once at load and cache. Source-of-truth
         *     for UI surfaces that render canonical Blizzard spelling
         *     (diacritics + capitalization preserved) and group heroes by
         *     role / maps by game type.
         */
        get: operations["GetReferenceData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/screenshots-folder-probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Probe the OS for the default Overwatch screenshots folder
         * @description Walks an ordered list of platform-specific candidate paths
         *     (Windows Documents + OneDrive-redirected variant; macOS
         *     Documents / Library Application Support; Linux Steam-Proton
         *     compatdata + standalone Wine prefix) and returns the first
         *     existing directory.
         *
         *     Read-only. Does NOT persist anything — the caller decides
         *     whether to apply the discovered path via
         *     `PUT /api/v1/settings/screenshots-folder`.
         *
         *     On first launch (when no folder is configured) the Wails
         *     runtime calls this internally and writes the result to
         *     `settings.json` directly; the HTTP endpoint serves the
         *     manual re-probe path (UI button "Detect Overwatch Folder").
         */
        get: operations["ProbeScreenshotsFolder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/tesseract-probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Probe the OS for an installed Tesseract binary
         * @description Walks an ordered list of per-platform candidate paths
         *     (Homebrew + MacPorts on macOS; apt / snap / Flatpak on Linux;
         *     Program Files + Chocolatey + per-user AppData + scoop on
         *     Windows) and returns the first one that resolves to a working
         *     Tesseract 5.x binary. Falls back to `PATH` lookup if none of
         *     the well-known locations match.
         *
         *     Each candidate is validated via the same `--version` check as
         *     `GET /api/v1/settings/tesseract` so a forgotten 3.x install
         *     on `PATH` doesn't "succeed" while producing wrong OCR output.
         *
         *     Read-only — does not persist. The caller (UI Detect button)
         *     decides whether to apply the discovered path via
         *     `PUT /api/v1/settings/tesseract`.
         */
        get: operations["ProbeTesseractBinary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/screenshots-folder-reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open the configured screenshots folder in the host OS file manager
         * @description Action endpoint — the effect (a Finder / Explorer / xdg-open
         *     window appearing on the server's host) is out-of-band relative
         *     to the HTTP response. The opener choice is per-platform:
         *
         *       * macOS:   `open <path>`
         *       * Linux:   `xdg-open <path>`
         *       * Windows: `explorer <path>`
         *
         *     The path is the in-memory `settings.ScreenshotsDir`, re-
         *     validated via the same `validateScreenshotsDir` boundary used
         *     by `PUT /api/v1/settings/screenshots-folder` before reaching
         *     the shell. Replaces an earlier frontend behavior that called
         *     `BrowserOpenURL('file://…')`, which Wails v2.12 rejects with
         *     "scheme not allowed".
         *
         *     No request body — the configured folder is the only thing
         *     this action can reveal, so passing an arbitrary path would
         *     widen the attack surface for no UX gain.
         */
        post: operations["RevealScreenshotsFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a full backup of the local parsed-match database
         * @description Returns a snapshot of the local database in one of two formats:
         *
         *       * `format=json` (default) — a single JSON document containing
         *         every per-screenshot row across all parent tables plus the
         *         screenshots-dirs lookup, wrapped in a schema-versioned
         *         envelope.
         *       * `format=csv` — a ZIP archive containing one CSV file per
         *         parent and child table plus a `manifest.json` with the
         *         envelope metadata. Same data version as the JSON variant
         *         (`schema = recall-export/v1`), different container chosen
         *         by users who want to inspect or edit the data in Excel /
         *         Sheets.
         *
         *     Both round-trip through `POST /api/v1/imports` — the server
         *     sniffs the first bytes to detect the format.
         */
        get: operations["ExportData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore the local database from a previously-exported backup
         * @description Replaces every row in the local database with the contents of
         *     the uploaded payload. Validates the envelope's `schema` field
         *     before touching the store; mismatched versions are rejected
         *     with `400` and the existing data is left untouched.
         *
         *     Accepts BOTH container formats — the server sniffs the payload's
         *     first bytes to detect a JSON envelope (`{` ...) or a ZIP archive
         *     (`PK\x03\x04` magic) and routes accordingly.
         *
         *     The operation is REPLACE, not merge: anything currently in the
         *     store is dropped after the payload is validated and before the
         *     import lands. Callers should surface a confirmation step.
         */
        post: operations["ImportData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream
         * @description Long-lived `text/event-stream` connection. Subscribers receive:
         *       * `parse-progress` — fired per OCR'd file during a parse run,
         *         carries `{done, total, filename, screenshot_type, match_key?, data?, error?}`.
         *         `match_key` is the resolved key for the just-inserted row
         *         (present on post-insert events; absent on the mid-OCR
         *         preview event). `error` is set when that single file failed
         *         to parse; the batch continues to the next file regardless,
         *         so the client should render a warning without aborting the
         *         in-flight UI.
         *       * `match-updated` — fired immediately after each successful
         *         per-screenshot insert, carrying the fully-aggregated
         *         `MatchRecord` for the affected `match_key`. Lets the
         *         frontend incrementally render the Matches list as a parse
         *         run progresses (upsert by `match_key`). Same shape as one
         *         element of `GET /api/v1/matches`. May fire multiple
         *         times for the same match within a single parse batch as
         *         additional screenshots refine its fields.
         *       * `parse-complete` — fired after a parse run finishes
         *       * Keepalive comment lines every 25 s so reverse proxies
         *         don't close the connection
         *
         *     Clients should reconnect on disconnect; messages are not
         *     replayed. After reconnect, the client should re-fetch
         *     `GET /api/v1/matches` as the authoritative reconciliation.
         */
        get: operations["Events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_screenshot/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve a screenshot image from the configured folder
         * @description Streams a file from the configured screenshots directory. The
         *     `{filename}` parameter must be a plain basename; path traversal
         *     (`..`, `/`, `\`) is rejected. Used by the frontend to render
         *     `<img>` previews without round-tripping bytes through the JSON
         *     bridge. Sits outside `/api/v1/` because it serves binary
         *     content, not JSON resources.
         */
        get: operations["GetScreenshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FolderPath: {
            /** @example /Users/jacob/Documents/Overwatch/ScreenShots/Overwatch */
            path: string;
        };
        ProbeResult: {
            /** @description True when at least one candidate directory existed. */
            found: boolean;
            /**
             * @description First existing candidate path. Empty when `found` is false.
             * @example /Users/jacob/Documents/Overwatch/ScreenShots/Overwatch
             */
            path?: string;
            /**
             * @description Ordered list of candidate paths inspected by the probe.
             *     Useful diagnostic when `found` is false — surfaces "we
             *     looked here and here" rather than a generic miss.
             * @example [
             *       "/Users/jacob/Documents/Overwatch/ScreenShots/Overwatch",
             *       "/Users/jacob/Documents/Blizzard/Overwatch/ScreenShots/Overwatch"
             *     ]
             */
            tried: string[];
        };
        DataLocation: {
            /**
             * @description Root directory Recall reads/writes from. Honors
             *     `RECALL_DATA_DIR`; otherwise the platform user-config
             *     directory.
             * @example /Users/jacob/Library/Application Support/Recall
             */
            base_dir: string;
            /**
             * @description Absolute path to `settings.json`.
             * @example /Users/jacob/Library/Application Support/Recall/settings.json
             */
            settings_path: string;
            /**
             * @description Absolute path to the SQLite database file.
             * @example /Users/jacob/Library/Application Support/Recall/db/recall.db
             */
            database_path: string;
            /**
             * @description Currently-configured screenshots folder. Empty string
             *     when not yet set.
             * @example /Users/jacob/Documents/Overwatch/Screenshots
             */
            screenshots_dir?: string;
        };
        /**
         * @description Schema-versioned envelope for the local backup format produced
         *     by `GET /api/v1/exports` and consumed by `POST /api/v1/imports`.
         *     The per-row arrays mirror the SQLite parent + child tables;
         *     the `screenshots_dirs` map carries the path-by-id reference so
         *     FKs survive the auto-increment reset that happens during
         *     import.
         */
        RecallExport: {
            /**
             * @description Envelope version. Current value `recall-export/v1`.
             * @example recall-export/v1
             */
            schema: string;
            exported_at?: string | null;
            /** @example 0.1.4 */
            recall_version?: string | null;
            /**
             * @description source-side `id` (stringified) → screenshots folder path
             * @example {
             *       "1": "/Users/jacob/Documents/Overwatch/Screenshots"
             *     }
             */
            screenshots_dirs?: {
                [key: string]: string;
            } | null;
            summaries?: Record<string, never>[] | null;
            scoreboards?: Record<string, never>[] | null;
            personals?: Record<string, never>[] | null;
            ranks?: Record<string, never>[] | null;
            unknowns?: Record<string, never>[] | null;
        };
        /**
         * @description One match — assembled by JOINing the per-screenshot-type rows
         *     that share the same `match_key`. Identity is `match_key`; no
         *     separate `id` exists because no single row underlies a match
         *     anymore.
         */
        MatchRecord: {
            /**
             * @description Stable identity. Either `match:<ISO-timestamp>` (from the
             *     earliest screenshot's filename) or `unmatched:<filename>` for
             *     files whose names didn't parse as timestamps.
             * @example match:2026-05-10T22:21:11
             */
            match_key: string;
            /**
             * @description Every screenshot filename that fed this match.
             * @example [
             *       "Overwatch Screenshot 2026.05.10 - 22.21.11.79.png",
             *       "Overwatch Screenshot 2026.05.10 - 22.21.57.34.png"
             *     ]
             */
            source_files: string[];
            /**
             * @description Per-source-file screenshot classification. Populated at
             *     parse time. May be absent on rows parsed before this column
             *     landed.
             * @example {
             *       "Overwatch Screenshot 2026.05.10 - 22.21.11.79.png": "scoreboard",
             *       "Overwatch Screenshot 2026.05.10 - 22.21.57.34.png": "rank"
             *     }
             */
            source_types?: {
                [key: string]: components["schemas"]["ScreenshotType"];
            };
            /**
             * @description Per-source-file timestamp (ISO8601) of when each screenshot
             *     was first inserted into the DB. Stable across subsequent
             *     re-parses of the same match. May be absent on rows / files
             *     persisted before this column landed.
             * @example {
             *       "Overwatch Screenshot 2026.05.10 - 22.21.11.79.png": "2026-05-10T22:30:00Z",
             *       "Overwatch Screenshot 2026.05.10 - 22.21.57.34.png": "2026-05-10T22:30:00Z"
             *     }
             */
            source_parsed_at?: {
                [key: string]: string;
            };
            /**
             * @description Per-source-file screenshots_dirs row id the file was ingested
             *     from. Frontends build `/_screenshot/{dir_id}/{filename}` URLs
             *     from this map so the screenshot handler can serve the right
             *     directory even after the user changes their screenshots
             *     folder (re-install, move, profile switch). Absent for rows
             *     where the dir was unset at parse time; clients should send
             *     `0` to fall back to the currently-configured screenshots
             *     folder.
             * @example {
             *       "Overwatch Screenshot 2026.05.10 - 22.21.11.79.png": 3,
             *       "Overwatch Screenshot 2026.05.10 - 22.21.57.34.png": 3
             *     }
             */
            source_dir_ids?: {
                [key: string]: number;
            };
            /**
             * Format: date-time
             * @description Match-level timestamp (ISO8601) of when the match record
             *     was first inserted into the DB. Stable across subsequent
             *     re-parses so the UI can display "parsed on X" without the
             *     value shifting when a later screenshot is added.
             * @example 2026-05-10T22:30:00Z
             */
            parsed_at?: string;
            data: components["schemas"]["MatchResult"];
            annotation?: components["schemas"]["MatchAnnotation"];
            /**
             * @description True iff the user soft-deleted this match via
             *     `PUT /api/v1/matches/{matchKey}/visibility`. Omitted (or
             *     false) for normal records. The per-screenshot parent rows
             *     are untouched — only the aggregator hides the surface.
             */
            hidden?: boolean;
            /**
             * @description True iff the resolver couldn't pin this screenshot to a
             *     single match (EAD signature match in the 5-30 min
             *     ambiguous window, or multiple candidates inside 30 min).
             *     The `match_key` carries the `ambiguous:<filename>`
             *     sentinel and the `candidates` array lists the possible
             *     matches the user can pick from in the Unknown tab.
             */
            ambiguous?: boolean;
            /**
             * @description Candidate matches this ambiguous screenshot could belong
             *     to. Only present when `ambiguous=true`. Sorted by
             *     `distance_seconds` ascending.
             */
            candidates?: components["schemas"]["AmbiguousCandidate"][];
        };
        /**
         * @description One candidate match an ambiguous screenshot could belong to.
         *     Populated by the resolver when EAD-bridge ambiguity is
         *     detected; surfaced to the user in the Unknown tab.
         */
        AmbiguousCandidate: {
            /**
             * @description The candidate match's `match_key`.
             * @example match:2026-05-10T21:29:28
             */
            match_key: string;
            /**
             * @description |Δt| between the ambiguous screenshot's filename timestamp
             *     and the candidate match's anchor timestamp, in seconds.
             * @example 720
             */
            distance_seconds: number;
        };
        /**
         * @description User-curated per-match metadata. Up to five optional fields —
         *     every field is independent, but the row only exists if at
         *     least one carries content. Omitted from `MatchRecord` when
         *     the match is unannotated.
         */
        MatchAnnotation: {
            /**
             * @description Which leaver scenario the user tagged this match with, or
             *     `""` if no leaver tag is set. `self` = user left (data
             *     incomplete); `team` = ally left; `enemy` = opponent left.
             * @enum {string}
             */
            leaver?: "" | "self" | "team" | "enemy";
            /** @description Free-text per-match commentary. */
            note?: string;
            /** @description Overwatch six-character replay ID. Stored verbatim. */
            replay_code?: string;
            /** @description BattleTags of group members for this match. */
            members?: string[];
            /**
             * @description Free-form match labels (lowercase, deduped). `stack`,
             *     `stream`, `placement` are the conventional three; users
             *     can add anything. Drives the FilterRail "Tags" filter.
             */
            tags?: string[];
            /**
             * Format: date-time
             * @description Server-set timestamp of when the annotation was last upserted.
             */
            annotated_at?: string;
        };
        /**
         * @description Classification of one screenshot:
         *       * `summary` — post-match SUMMARY tab
         *       * `scoreboard` — in-game or post-match TEAMS scoreboard
         *       * `personal` — post-match PERSONAL tab
         *       * `rank` — competitive RANK PROGRESS screen
         *       * `unknown` — the OCR classifier couldn't pick a type from
         *         the file. Surfaced in the Unknown tab for triage; the
         *         row's per-screenshot data lives in `unknown_screenshots`
         *         until the user resolves it (re-OCR, manual attribution,
         *         or drop).
         * @enum {string}
         */
        ScreenshotType: "summary" | "scoreboard" | "personal" | "rank" | "unknown";
        /** @description All parsed data for a match, merged across its source files. */
        MatchResult: {
            /** @description e.g. "rialto" */
            map?: string;
            /** @description e.g. "control" */
            type?: string;
            /** @enum {string} */
            mode?: "competitive" | "quickplay" | "unranked" | "";
            /** @enum {string} */
            role?: "tank" | "dps" | "support" | "";
            /** @description Primary (most-played) hero */
            hero?: string;
            eliminations?: number;
            assists?: number;
            deaths?: number;
            damage?: number;
            healing?: number;
            mitigation?: number;
            /** @enum {string} */
            result?: "victory" | "defeat" | "draw" | "";
            /** @example 3-1 */
            final_score?: string;
            /** @example 2026-05-10 */
            date?: string;
            /**
             * @description HH:MM 24h as shown by the OW client.
             * @example 21:29
             */
            finished_at?: string;
            /** @example 11:25 */
            game_length?: string;
            heroes_played?: components["schemas"]["HeroPlay"][];
            performance?: components["schemas"]["Performance"];
            /** @example platinum */
            rank?: string;
            level?: number;
            /**
             * @example [
             *       "expected",
             *       "victory"
             *     ]
             */
            modifiers?: string[];
            rank_progress?: number;
            /** @description Percentage the rank moved this match (signed). */
            change_percent?: number;
            sr?: components["schemas"]["HeroSR"][];
        };
        HeroPlay: {
            /** @example lucio */
            hero: string;
            /** @example 100 */
            percent_played: number;
            /** @example 11:25 */
            play_time?: string;
            /**
             * @description Hero-specific stats keyed by snake_case label.
             * @example {
             *       "weapon_accuracy": 24,
             *       "players_saved": 6
             *     }
             */
            stats?: {
                [key: string]: number;
            };
        };
        HeroSR: {
            /** @example lucio */
            hero: string;
            /** @example 2754 */
            sr: number;
            /**
             * @description Signed delta this match
             * @example 30
             */
            change: number;
        };
        Performance: {
            eliminations?: components["schemas"]["PerformanceStat"];
            assists?: components["schemas"]["PerformanceStat"];
            deaths?: components["schemas"]["PerformanceStat"];
        };
        PerformanceStat: {
            total: number;
            /** Format: double */
            avg_per_10min?: number;
        };
        ProfilesResponse: {
            /**
             * @description The currently-active profile name.
             * @example main
             */
            active: string;
            /**
             * @description Sorted list of every known profile name.
             * @example [
             *       "alt",
             *       "main"
             *     ]
             */
            profiles: string[];
        };
        TesseractStatus: {
            /**
             * @description The currently-configured path.
             * @example /opt/homebrew/bin/tesseract
             */
            path: string;
            /** @description True iff `path` resolves to a working binary. */
            found: boolean;
            /** @description Tesseract `--version` output (e.g. "5.4.1"). Empty when not found. */
            version: string;
            /** @description True iff the detected major version is 5.x (the only officially supported series). */
            supported: boolean;
            /** @description Description of the last detection failure, if any. */
            error: string;
            /** @description Platform default path (Homebrew on macOS, /usr/bin on Linux, etc.). */
            default: string;
            /**
             * @description Host's `runtime.GOOS` value — `darwin`, `linux`, `windows`,
             *     `freebsd`, etc. The frontend uses it to surface only the
             *     install-path guidance that matches the host, instead of
             *     listing every OS in one confusing paragraph.
             * @example darwin
             */
            platform: string;
        };
        EnabledFlag: {
            enabled: boolean;
        };
    };
    responses: {
        /** @description Malformed request body or query parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description The requested resource was not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Unhandled server-side error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
    };
    parameters: {
        /**
         * @description Match identity — same `match_key` exposed in `MatchRecord`.
         *     URL-encoded because the value normally contains a colon
         *     (e.g. `match:2026-05-10T22:21:11`).
         * @example match%3A2026-05-10T22%3A21%3A11
         */
        MatchKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetMatchResults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of match records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRecord"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    ClearMatches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All matches cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
        };
    };
    HardDeleteMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Match identity — same `match_key` exposed in `MatchRecord`.
                 *     URL-encoded because the value normally contains a colon
                 *     (e.g. `match:2026-05-10T22:21:11`).
                 * @example match%3A2026-05-10T22%3A21%3A11
                 */
                matchKey: components["parameters"]["MatchKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Match removed (or already absent). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    SetMatchVisibility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Match identity — same `match_key` exposed in `MatchRecord`.
                 *     URL-encoded because the value normally contains a colon
                 *     (e.g. `match:2026-05-10T22:21:11`).
                 * @example match%3A2026-05-10T22%3A21%3A11
                 */
                matchKey: components["parameters"]["MatchKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description True to hide; false to unhide. */
                    hidden: boolean;
                };
            };
        };
        responses: {
            /** @description Visibility updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    ResolveAmbiguousMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Match identity — same `match_key` exposed in `MatchRecord`.
                 *     URL-encoded because the value normally contains a colon
                 *     (e.g. `match:2026-05-10T22:21:11`).
                 * @example match%3A2026-05-10T22%3A21%3A11
                 */
                matchKey: components["parameters"]["MatchKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The match the user picked. Must be one of the
                     *     recorded candidates or a `match:<...>` key.
                     * @example match:2026-05-10T21:29:28
                     */
                    resolved_to: string;
                };
            };
        };
        responses: {
            /** @description Resolution applied. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    SetMatchAnnotation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Match identity — same `match_key` exposed in `MatchRecord`.
                 *     URL-encoded because the value normally contains a colon
                 *     (e.g. `match:2026-05-10T22:21:11`).
                 * @example match%3A2026-05-10T22%3A21%3A11
                 */
                matchKey: components["parameters"]["MatchKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description One of the three leaver scenarios, or `""` to leave
                     *     untagged. Whole-row deletion happens only when *every*
                     *     field (leaver, note, replay_code, members, tags) is
                     *     empty.
                     * @enum {string}
                     */
                    leaver?: "" | "self" | "team" | "enemy";
                    /** @description Free-text per-match commentary. `null` = empty. */
                    note?: string | null;
                    /** @description Overwatch six-character replay ID. No format validation server-side. `null` = empty. */
                    replay_code?: string | null;
                    /**
                     * @description BattleTags of group members for this match. The server
                     *     trims whitespace, drops empty strings, and deduplicates;
                     *     the composite-PK on the child table catches any
                     *     duplicates that slip through. `null` is treated as an
                     *     empty list (clear members) — equivalent to `[]`.
                     */
                    members?: string[] | null;
                    /**
                     * @description Free-form labels applied to the match. `stack`,
                     *     `stream`, and `placement` are the conventional
                     *     three (the UI surfaces them as quick-add toggles)
                     *     but any string is accepted. Server lowercases +
                     *     trims + deduplicates before persistence so
                     *     `Stack` and `stack` collapse to one entry. Drives
                     *     the FilterRail "Tags" multi-select. `null` is
                     *     treated as an empty list (clear tags) — equivalent
                     *     to `[]`.
                     */
                    tags?: string[] | null;
                };
            };
        };
        responses: {
            /** @description Annotation persisted or cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    ParseScreenshots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Parse run complete; subscribe to events for incremental updates. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    GetPendingScreenshotCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Count. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 3 */
                        count: number;
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    GetScreenshotsFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current path. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderPath"];
                };
            };
        };
    };
    SetScreenshotsFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderPath"];
            };
        };
        responses: {
            /** @description New path echoed back. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderPath"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    ResetScreenshotsFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
        };
    };
    GetTesseractSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current engine status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TesseractStatus"];
                };
            };
        };
    };
    SetTesseractPath: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example /opt/homebrew/bin/tesseract */
                    path: string;
                };
            };
        };
        responses: {
            /** @description Re-detected status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TesseractStatus"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    ResetTesseractPath: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Re-detected status against the default path. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TesseractStatus"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    GetPrometheusEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnabledFlag"];
                };
            };
        };
    };
    SetPrometheusEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnabledFlag"];
            };
        };
        responses: {
            /** @description Toggle applied. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    GetWatchEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnabledFlag"];
                };
            };
        };
    };
    SetWatchEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnabledFlag"];
            };
        };
        responses: {
            /** @description Toggle applied. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    GetProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active + list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilesResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    CreateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Profile name. Must match `^[a-zA-Z0-9][a-zA-Z0-9_-]{0,39}$`
                     *     (filesystem-safe).
                     * @example alt
                     */
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created and activated. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    SwitchProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example main */
                    name: string;
                };
            };
        };
        responses: {
            /** @description Switched. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    RenameProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description New profile name. Same regex as creation:
                     *     `^[a-zA-Z0-9][a-zA-Z0-9_-]{0,39}$`.
                     * @example silentstorm
                     */
                    new_name: string;
                };
            };
        };
        responses: {
            /** @description Renamed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description A profile with that new name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    DeleteProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Profile is active; switch away first. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    MoveMatches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    match_keys: string[] | null;
                    target_profile: string;
                };
            };
        };
        responses: {
            /** @description Move complete. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description target_profile is the active profile. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    GetVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current build version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 0.0.13-beta.0 */
                        version: string;
                    };
                };
            };
        };
    };
    CheckForUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Update availability info. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description True when a GitHub API call completed successfully.
                         *     False on network failure — show nothing in that case.
                         * @example true
                         */
                        checked: boolean;
                        /**
                         * @description True when the running version is a dev build. The
                         *     latest release is then informational context, not an
                         *     upgrade prompt.
                         * @example false
                         */
                        dev_build: boolean;
                        /**
                         * @description True when the latest release is newer than the running
                         *     version (only meaningful when dev_build=false).
                         * @example true
                         */
                        available: boolean;
                        /** @example 0.0.15 */
                        latest: string;
                        /** @example https://github.com/sound-barrier/recall/releases/tag/v0.0.15 */
                        url: string;
                    };
                };
            };
        };
    };
    GetDataLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Path inventory. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataLocation"];
                };
            };
        };
    };
    GetReferenceData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The embedded OW reference data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Hero names grouped by role, alphabetised within each role.
                         * @example {
                         *       "tank": [
                         *         "Doomfist",
                         *         "D.va",
                         *         "Reinhardt"
                         *       ],
                         *       "dps": [
                         *         "Ashe",
                         *         "Genji",
                         *         "Tracer"
                         *       ],
                         *       "support": [
                         *         "Ana",
                         *         "Juno",
                         *         "Mercy"
                         *       ]
                         *     }
                         */
                        heroes_by_role: {
                            [key: string]: string[];
                        };
                        /**
                         * @description Map names grouped by game type, alphabetised within each type.
                         * @example {
                         *       "control": [
                         *         "Antarctic Peninsula",
                         *         "Busan",
                         *         "Nepal"
                         *       ],
                         *       "escort": [
                         *         "Dorado",
                         *         "Watchpoint Gibraltar"
                         *       ],
                         *       "hybrid": [
                         *         "King's Row",
                         *         "Midtown"
                         *       ]
                         *     }
                         */
                        maps_by_type: {
                            [key: string]: string[];
                        };
                    };
                };
            };
        };
    };
    ProbeScreenshotsFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Probe result. `found: true` carries the discovered path;
             *     `found: false` includes the full `tried` list for the
             *     user to inspect.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
        };
    };
    ProbeTesseractBinary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Probe result. `found: true` carries the discovered path;
             *     `found: false` includes the full `tried` list for the
             *     user to inspect.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
        };
    };
    RevealScreenshotsFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Opener spawned. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    ExportData: {
        parameters: {
            query?: {
                /** @description Wire format. Defaults to JSON. */
                format?: "json" | "csv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export download. */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecallExport"];
                    "application/zip": string;
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    ImportData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecallExport"];
                "application/zip": string;
            };
        };
        responses: {
            /** @description Import applied. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Malformed or wrong-schema payload. Body is a plain-text
             *     error message safe to surface to the user.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    Events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    GetScreenshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description URL-encoded basename of a file in the screenshots folder.
                 * @example Overwatch%202%20Screenshot%202026.05.10%20-%2021.49.34.41.png
                 */
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/jpeg": string;
                };
            };
            /** @description Malformed path or filename. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found, no folder configured, or path traversal rejected. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
