#!/usr/bin/env bash
# Cyclomatic-complexity sweep — REPORT ONLY.
#
# Two passes:
#   1. gocyclo over the Go source (whole module, minus the embed
#      sentinel under frontend/node_modules/flatted).
#   2. ESLint with a minimal flat config that runs ONLY the
#      `complexity` rule against frontend/src/**/*.{ts,vue}.
#
# Findings are printed; the script ALWAYS exits 0. The goal is
# situational awareness across PRs, not a gate. When a number climbs
# into "this needs a refactor" territory, raise a REVIEW.md
# item — don't tighten the threshold here.
#
# Consumed from:
#   - Makefile               → `make complexity` (and sub-targets)
#   - lefthook.yml           → pre-push.complexity (non-blocking)
#   - .github/workflows/ci.yml → `complexity` job (non-blocking)
#
# Threshold (McCabe's 1976 recommendation): 10. Tune in one place
# below — the constants drive both the Go and frontend sweeps.

set -u

THRESHOLD=10
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT" || exit 1

# Resolve gocyclo via tool-versions.env so the pin matches the rest of
# the repo. `go install` is a no-op when the binary is already on
# $GOBIN at the right version. shellcheck `disable=SC1091` because
# the env file is generated by humans + auto-sourced from many
# scripts; we trust its shape.
# shellcheck disable=SC1091
. ./tool-versions.env

GOCYCLO="$(command -v gocyclo || true)"
if [[ -z "$GOCYCLO" ]]; then
  if ! command -v go >/dev/null; then
    echo "[complexity] go toolchain not installed — skipping Go pass."
    exit 0
  fi
  echo "[complexity] gocyclo not on PATH — bootstrapping via go install ${GOCYCLO_VERSION}…"
  go install "github.com/fzipp/gocyclo/cmd/gocyclo@${GOCYCLO_VERSION}"
  GOCYCLO="$(go env GOPATH)/bin/gocyclo"
fi

echo "── Go (gocyclo -over ${THRESHOLD}) ──────────────────────────────────"
# gocyclo exits non-zero when it finds anything over the threshold;
# we swallow that and a stderr from its missing-import warnings on a
# barely-bootstrapped module. The exclusion at the end is for the
# flatted stub Go's walker would otherwise pick up.
"$GOCYCLO" -over "$THRESHOLD" . 2>/dev/null \
  | grep -v "/frontend/node_modules/" \
  || echo "(no Go functions above ${THRESHOLD})"

echo
echo "── Frontend (eslint complexity > ${THRESHOLD}) ──────────────────────"
if command -v npx >/dev/null; then
  # ESLint exits 0 with only warnings (which is what `complexity: warn`
  # produces), so no `|| true` needed — but we still guard against
  # missing node_modules on a clean checkout.
  if [[ -d frontend/node_modules ]]; then
    # Filter to ONLY complexity findings (+ the file headers that
    # precede them). The minimal config doesn't load other rules, but
    # files with `eslint-disable-next-line <some-other-rule>` produce
    # noisy "rule definition not found" errors we want to drop.
    (cd frontend && npx --no-install eslint \
      --config eslint.complexity.config.js \
      'src/**/*.{ts,vue}' 2>&1) \
      | awk '
        /complexity/ { active=1; if (header) { print header; header="" } print; next }
        /^\/.*\.(ts|vue)$/ { header=$0; active=0; next }
        /^[[:space:]]*✖/ { if (active) print }
      ' \
      || true
  else
    echo "(frontend/node_modules absent — skipping; run \`npm --prefix frontend ci\` first)"
  fi
else
  echo "(npx not installed — skipping frontend pass)"
fi

echo
echo "[complexity] sweep complete — REPORT ONLY (no enforcement)."
exit 0
