// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {http} from '../models';

export function GetMatchResults():Promise<Array<main.MatchRecord>>;

export function GetPrometheusEnabled():Promise<boolean>;

export function GetScreenshotsDir():Promise<string>;

export function ParseScreenshots():Promise<void>;

export function PickScreenshotsDir():Promise<string>;

export function ScreenshotHandler():Promise<http.Handler>;

export function SetPrometheusEnabled(arg1:boolean):Promise<void>;
