// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMatchResults():Promise<Array<main.MatchRecord>>;

export function ParseScreenshots():Promise<void>;
