// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMatchResults() {
  return window['go']['main']['App']['GetMatchResults']();
}

export function ParseScreenshots() {
  return window['go']['main']['App']['ParseScreenshots']();
}
