// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMatchResults() {
  return window['go']['main']['App']['GetMatchResults']();
}

export function GetScreenshotsDir() {
  return window['go']['main']['App']['GetScreenshotsDir']();
}

export function ParseScreenshots() {
  return window['go']['main']['App']['ParseScreenshots']();
}

export function PickScreenshotsDir() {
  return window['go']['main']['App']['PickScreenshotsDir']();
}

export function ScreenshotHandler() {
  return window['go']['main']['App']['ScreenshotHandler']();
}
